fix(docs): update cognito provider doc
nextauthjs/next-auth pull request #10622
Opened 2024-04-17 16:03 UTC by markCwatson

Requested on [PR#10600](https://github.com/nextauthjs/next-auth/pull/10600)

2024-04-17 16:04 UTC, markCwatson commented
@ndom91 I do not trust my local MDX processor... so not 100% confident on how this looks

2024-04-17 16:15 UTC, ndom91 approved these changes
LGTM to me :wink: 

![image](https://github.com/nextauthjs/next-auth/assets/7415984/4ee8106a-ab9f-4636-a3d9-f67531530e9a)

2024-04-17 16:18 UTC, ndom91 requested changes

2024-04-17 16:18 UTC, ndom91 commented on docs/pages/getting-started/providers/cognito.mdx
> +The **Amazon Cognito Provider** comes with a set of default options:
Although this whole part about the options just links to the code for the provider, this is kind of implied.. 

Let's get rid of this part and keep the Callout about the hosted domain settings as well as the link for hosted domain above, thanks!

2024-04-17 17:44 UTC, ndom91 approved these changes

2024-04-17 19:40 UTC, markCwatson commented
@ndom91 @ubbe-xyz and I expected to merge latest changes from `main` (and merge?)?

2024-04-18 11:31 UTC, ndom91 commented
@markCwatson yeah this looks good now, thanks!

2024-04-18 11:32 UTC, merged