hey i added the logo to the readme file
nextauthjs/next-auth pull request #1087
Opened 2021-01-11 13:49 UTC by suraj10k

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

2021-01-11 14:30 UTC, balazsorban44 requested changes

2021-01-11 14:30 UTC, balazsorban44 commented on ss
> +[33mcommit 7a1d7120965a01ba23e62277989f4032aa9c9916[m[33m ([m[1;36mHEAD -> [m[1;32mcanary[m[33m, [m[1;33mtag: v3.2.0-canary.14[m[33m, [m[1;31morigin/canary[m[33m, [m[1;31morigin/HE
This file should be deleted.

2021-01-11 14:31 UTC, balazsorban44 commented
Also, look at this to how to add the banner to the site footer:

https://github.com/nextauthjs/next-auth/issues/1035#issuecomment-757906694

2021-01-11 14:33 UTC, balazsorban44 commented on README.md
> +<img width="170px" src="https://raw.githubusercontent.com/nextauthjs/next-auth/7a1d7120965a01ba23e62277989f4032aa9c9916/www/static/img/powered-by-vercel.svg" alt="Banner" />
I would use `Powered by Vercel` as an alt text, to be more descriptive

2021-01-11 14:33 UTC, suraj10k commented on ss
> +[33mcommit 7a1d7120965a01ba23e62277989f4032aa9c9916[m[33m ([m[1;36mHEAD -> [m[1;32mcanary[m[33m, [m[1;33mtag: v3.2.0-canary.14[m[33m, [m[1;31morigin/canary[m[33m, [m[1;31morigin/HE
deleted

2021-01-11 14:33 UTC, balazsorban44 commented on README.md
> +<p allign="left">Thanks to Vercel sponsoring this project by allowing it to be deployed for free for the entire NextAuth.js Team</p>
there is a typo here, it should be `align`

2021-01-11 14:34 UTC, balazsorban44 commented
Could you also remove this line:

https://github.com/nextauthjs/next-auth/blob/e7e8e0f3932eee767641ec07fc27ef16f71413eb/www/src/pages/index.js#L186

2021-01-11 14:41 UTC, suraj10k commented
> Could you also remove this line:
> 
> https://github.com/nextauthjs/next-auth/blob/e7e8e0f3932eee767641ec07fc27ef16f71413eb/www/src/pages/index.js#L186

done , ill now work on adding the banner to the site footer

2021-01-11 19:10 UTC, balazsorban44 commented on README.md
> +<img width="170px" src="https://raw.githubusercontent.com/nextauthjs/next-auth/7a1d7120965a01ba23e62277989f4032aa9c9916/www/static/img/powered-by-vercel.svg" alt="Powered By Vercel" />
Could you use this as a url `https://raw.githubusercontent.com/nextauthjs/next-auth/canary/www/static/img/powered-by-vercel.svg` to the banner?

2021-01-12 12:31 UTC, balazsorban44 commented
> > Could you also remove this line:
> > https://github.com/nextauthjs/next-auth/blob/e7e8e0f3932eee767641ec07fc27ef16f71413eb/www/src/pages/index.js#L186
> 
> done , ill now work on adding the banner to the site footer

Awesome, tell me when it is done, then we are good to go!

2021-01-12 16:47 UTC, suraj10k commented
when i try to start the localhost with "npm run dev" i'm getting : "npm run dev
npm ERR! missing script: dev" . could you pls help me fix this . im new to working with react

2021-01-12 18:39 UTC, balazsorban44 commented
So to start the documentation site, you should be inside the `www` folder, run `npm i`, and run `npm start`. You will then be able to see the documentation at `http://localhost:3000`

To add the banner as a link to the footer under acknowledgments, you can see the Docosaurus docs here:
https://v2.docusaurus.io/docs/api/themes/configuration/#footer-links


I created the snippet you should add as:


```js
{html: `
  <a target="_blank" rel="noopener noreferrer" href="https://vercel.com?utm_source=next-auth&utm_campaign=oss">
    <img
      alt="Powered by Vercel"
      style="margin-top: 8px"
      height="32"
      src="https://raw.githubusercontent.com/nextauthjs/next-auth/canary/www/static/img/powered-by-vercel.svg"
    />
  </a>`
}
```

The relevant part of the file you would like to add this to is after this: https://github.com/nextauthjs/next-auth/blob/0c405295350ce211ec9bda3d63ca76fbdb3655b4/www/docusaurus.config.js#L96-L99

2021-01-12 18:53 UTC, suraj10k commented
Thanks a lot I'll try it

2021-01-13 18:28 UTC, merged

2021-01-13 18:34 UTC, balazsorban44 commented
@suraj10k, thanks for your contribution!

2021-01-14 00:47 UTC, suraj10k commented
Can I get listed as a contributor ?

2021-01-14 01:23 UTC, balazsorban44 commented
You can see yourself at this url:

https://github.com/nextauthjs/next-auth/graphs/contributors

We currently don't have anything similar to https://allcontributors.org set up.

2021-01-14 01:44 UTC, suraj10k commented
got it ,thanks a lot, this was my first open source contribution and even thoguh it was a simple one i learnt a lot.

2021-01-14 10:37 UTC, balazsorban44 commented
Awesome! Good to hear! 🙂 Good luck on your journey! 😉