Fauna adapter - Fixes in getSession
nextauthjs/next-auth pull request #1134
Opened 2021-01-17 00:35 UTC by pbteja1998

Fixes #1131 

**What**:
`session.data.expires` that we get from Fauna DB is in `Fauna.Time` format. In this PR, I am converting it into milliseconds.

**Why**:
Session not being persisted when browser is closed because of invalid `expiresAt` date

**Checklist**:

- [N/A] Documentation
- [N/A] Tests
- [x] Ready to be merged

2021-01-17 21:22 UTC, balazsorban44 requested changes
Looks like there are linting errors, could you fix those at least so builds don't fail? :) @pbteja1998

2021-01-18 00:25 UTC, ndom91 approved these changes

2021-01-18 18:37 UTC, balazsorban44 commented
So sorry for this @pbteja1998, but we decided to drop builtin support for Fauna DB for now. it will be removed soon in a later release. it is a bit of an overhead to make sure it works, while there aren't even tests for it. As you did as well so good, it is still possible to use it with the custom adapter option. 😉

2021-01-18 18:37 UTC, closed without merging

2021-01-18 18:40 UTC, pbteja1998 commented
> So sorry for this @pbteja1998, but we decided to drop builtin support for Fauna DB for now. it will be removed soon in a later release. it is a bit of an overhead to make sure it works, while there aren't even tests for it. As you did as well so good, it is still possible to use it with the custom adapter option. 😉

Not a problem. It works for my use-case. So it's OK.