chore(docs): add client-side support for magic links using Next.js
nextauthjs/next-auth pull request #11691
Opened 2024-08-28 00:45 UTC by halvaradop

## ☕️ Reasoning
This pull request adds code to the `getting-started/authentication` section for implementing magic links. It allows users to authenticate using magic links, providing a secure and user-friendly login method. The code demonstrates the client-side implementation in Next.js.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2024-09-04 09:04 UTC, balazsorban44 requested changes
See https://github.com/nextauthjs/next-auth/pull/11701#discussion_r1743351168

2024-09-04 17:22 UTC, halvaradop commented
I have made changes similar to those in PR #11701. I added `Object.fromEntries` because the `signIn` function expects a value of type `SignInOptions`, which is an object. Additionally, I included the `"use client"` directive to indicate that the component works on the client side. We can discuss further if you have any questions or concerns about these changes.

2024-09-15 14:22 UTC, balazsorban44 commented on docs/pages/getting-started/authentication/email.mdx
> +    signIn("resend", Object.fromEntries(formData))
```suggestion
  const resendAction = (formData: FormData) => {
    signIn("resend", formData)
```

You can pass FormData in, we convert it automatically https://github.com/nextauthjs/next-auth/blob/965f41e0d177ed6e5e30e9b48b6ea081f2e99194/packages/next-auth/src/lib/actions.ts#L23

2024-09-15 14:23 UTC, balazsorban44 commented on docs/pages/getting-started/authentication/email.mdx
> +    signIn("sendgrid", Object.fromEntries(formData))
```suggestion
  const sendgridAction = (formData: FormData) => {
    signIn("sendgrid", formData)
```

2024-09-15 14:26 UTC, merged