Fix #11944 - Removed explicit undefined values before passing to Prisma
nextauthjs/next-auth pull request #11945
Opened 2024-10-01 20:49 UTC by petergoldstein

## ☕️ Reasoning

This addresses #11944 - Prisma now throws errors if you pass explicit undefined values as part of a create, if you have the preview feature "strictUndefinedChecks" on.  So this change filters out any explicit undefined values.  It has no tests, and was done in the simplest possible way.  I'm looking for feedback on the implementation to prepare for a merge and how you might want to see it tested.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Fixes: #11944 

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2024-10-01 21:55 UTC, balazsorban44 requested changes
Let's abstract this into a `stripUndefined` method in the module scope

2024-10-01 22:25 UTC, petergoldstein commented
@balazsorban44 Pulled out to a module scoped function.

Regarding the schema, do you envision adding another schema file for testing?  Or updating one or more of the existing files with the preview setting?

2024-10-01 22:41 UTC, balazsorban44 commented
we van update all existing ones. 👍 if this becomes the default, we should test it already. the current flow has been battle tested pretty throughly, already.

2024-10-01 22:50 UTC, balazsorban44 commented
we ca ln update all existing ones. 👍 if this becomes the default, we should test it already. the current flow has been battle tested pretty throughly, already.

Also, I, wonder if using the `Prisma.skip` symbol as a fallback is the correct path, per prisma docs https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/null-and-undefined#migration-path

WDYT?

2024-10-02 00:32 UTC, petergoldstein commented
Using Prisma.skip is fine, but it doesn't actually make a ton of sense in this context.  The change is there to prevent inadvertent deletions of updates, and the impact on the data hash passed to a create or update is basically a by-product.  But use of Prisma.skip requires that the preview feature be active.  This approach works for both cases - flag active or not.

I will probably need some help updating the libraries - my local environment is giving me issues on a `pnpm install`.  But if someone else can do that, i can make the generator changes.

2024-10-02 19:45 UTC, balazsorban44 commented
Superseded by #11952

2024-10-02 19:45 UTC, closed without merging