Fixes: #11992 - awaited headers and cookies
nextauthjs/next-auth pull request #12002
Opened 2024-10-08 20:07 UTC by Code-DJ

Fixes: #11992

Added await for headers and cookies.

Ran the following script to find issues:
```sh
bunx @next/codemod@canary next-async-request-api .
```

2024-10-08 23:09 UTC, balazsorban44 requested changes

2024-10-08 23:09 UTC, balazsorban44 commented on packages/next-auth/src/lib/index.ts
> +      return getSession((headers() as unknown as UnsafeUnwrappedHeaders), config).then((r) => r.json())
let's chain this with `.then` instead to be able to get rid of the unsafe type

2024-10-17 13:03 UTC, neoromantic commented
Eagerly waiting for this one to be merged!

2024-10-17 21:14 UTC, iFlyinq commented
Thanks for this contribution! ;)

2024-10-18 20:11 UTC, iFlyinq commented
If you'd like to say something @richardasymmetric feel free to do so, instead of disliking without feedback :P

2024-10-19 00:35 UTC, richardasymmetric commented
Sorry for adding to the noise, everyone subscribed!

Hi @iFlyinq, you're one of [today's lucky 10,000](https://xkcd.com/1053/)! 😊

> If you'd like to say something @richardasymmetric feel free to do so, instead of disliking without feedback :P

I appreciate your enthusiasm, and I see how the comment was meant to express gratitude! However, I tend to thumbs down comments that, while maybe positive, don't necessarily add new technical information to the discussion. This includes comments like "me too," "+1," or "when will this be fixed?". GitHub notifies everyone subscribed to the issue for every comment, and even well-meaning comments like "Thanks for this contribution!" or similar can add to the noise for people who are closely following the thread for updates or technical input.

If you'd like to show support or appreciation for the issue, reactions (👍, 👎, etc.) are a great alternative. They help keep the thread focused while still letting contributors know their work is appreciated. Thanks for understanding, and I hope this helps clarify my reasoning!

2024-10-19 19:51 UTC, gnoff commented on packages/next-auth/src/lib/actions.ts
> +  for (const c of res?.cookies ?? []) (await cookies()).set(c.name, c.value, c.options)
probably better off pulling this out of the loop

2024-10-19 19:51 UTC, gnoff commented on packages/next-auth/src/lib/actions.ts
> +  for (const c of res?.cookies ?? []) (await cookies()).set(c.name, c.value, c.options)
same here

2024-10-19 19:53 UTC, closed without merging

2024-10-19 20:20 UTC, balazsorban44 commented
A fix for this should be out in `next-auth@5.0.0-beta.24` :tada:!