Correct the type signature of `account` in callbacks.
nextauthjs/next-auth pull request #12017
Opened 2024-10-09 20:11 UTC by w9

## ☕️ Reasoning

The `account` argument can be `undefined` if it's not immediately after a sign-in. The current type signature does not reflect that.

## 🧢 Checklist

- [x] Documentation (Not applicable)
- [x] Tests
- [x] Ready to be merged

2024-10-29 22:07 UTC, newcloudreboss approved these changes

2024-11-01 00:31 UTC, balazsorban44 requested changes

2024-11-01 00:31 UTC, balazsorban44 commented on packages/core/src/index.ts
> +      account: Account | null | undefined
```suggestion
      account?: Account | null
```

2024-11-01 00:31 UTC, balazsorban44 commented on packages/core/src/index.ts
> +      account: Account | null | undefined
```suggestion
      account?: Account | null
```

2024-11-01 00:31 UTC, balazsorban44 commented on packages/core/src/index.ts
> +      account: Account | null | undefined
```suggestion
      account?: Account | null
```

2024-11-01 00:32 UTC, merged