fix: Updated twitter icon
nextauthjs/next-auth pull request #12091
Opened 2024-10-21 19:19 UTC by sarthak-kumar-shailendra

## ☕️ Reasoning
The Twitter logo has been changed and hasn't been updated on the site. [Fixes #12090]
After changes
<img width="816" alt="Screenshot 2024-10-22 at 12 35 58 AM" src="https://github.com/user-attachments/assets/99460c8c-a614-4f77-b0d2-72647c3d9ff5">
<img width="873" alt="Screenshot 2024-10-22 at 12 36 10 AM" src="https://github.com/user-attachments/assets/8c09ecae-15c0-472b-a6e8-02de3c6bebbf">

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2024-10-28 18:25 UTC, sarthak-kumar-shailendra commented
@balazsorban44 Please review

2024-10-28 18:47 UTC, ndom91 approved these changes
Please don't directly tag the maintainers 🙏 

Good catch though, thanks!

2024-10-28 18:52 UTC, ndom91 commented on docs/public/img/providers/twitter.svg
> +<svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 30 30" width="480px" height="480px"><path d="M26.37,26l-8.795-12.822l0.015,0.012L25.52,4h-2.65l-6.46,7.48L11.28,4H4.33l8.211,11.971L12.54,15.97L3
Actually, can you remove the hard coded height/width and additional extra space before 'viewBox'? Thanks!

2024-11-01 00:25 UTC, balazsorban44 requested changes
I think we should create a new X provider instead, and mark twitter as deprecated.

2025-02-02 08:18 UTC, merged