fix(nextjs): Update params type with Promise as expected in Next.js 15
nextauthjs/next-auth pull request #12114
Opened 2024-10-24 20:53 UTC by ggallon

## ☕️ Reasoning

Follow #12002, fix type error with auth() wapprer,  update params type with Promise in handler.
Ref: [Next.js Doc](https://nextjs.org/docs/canary/app/api-reference/file-conventions/route#context-optional)

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2024-10-24 20:59 UTC, balazsorban44 requested changes
Thanks! I believe we should use our `Awaitable` here from `@auth/core/types`, to be compatible with Next.js 14.

2024-10-24 21:17 UTC, ggallon commented
@balazsorban44, It's done

2024-10-25 17:56 UTC, ggallon commented
@balazsorban44 sorry, that's not the way. `pnpm tsc --noEmit` in locale not always cause an error (??) but every time with `pnpm next build`:
```
Type "AppRouteHandlerFnContext" is not a valid type for the function's second argument.
    Expected "Promise<any>", got "Awaitable<Record<string, string | string[]>> | undefined".
      Expected "Promise<any>", got "undefined".
````

2024-10-28 19:22 UTC, Aralf commented
> @balazsorban44 sorry, that's not the way. `pnpm tsc --noEmit` in locale not always cause an error (??) but every time with `pnpm next build`:
> 
> ```
> Type "AppRouteHandlerFnContext" is not a valid type for the function's second argument.
>     Expected "Promise<any>", got "Awaitable<Record<string, string | string[]>> | undefined".
>       Expected "Promise<any>", got "undefined".
> ```

@ggallon as the error mentions, `undefined` is not valid, that's because `params` is set as optional, it shouldn't be.

2024-10-31 07:10 UTC, rpavlovs commented on packages/next-auth/src/lib/types.ts
> +  params?: Awaitable<Record<string, string | string[]>>
```suggestion
  params: Awaitable<Record<string, string | string[]>>
```

2024-11-01 00:22 UTC, merged

2024-11-13 15:43 UTC, rpavlovs commented
@balazsorban44 could you please bump the npm package version?

2024-11-20 08:17 UTC, rpavlovs commented
@balazsorban44 Please make an npm push. This is blocking Next 15, React 19 update.