feat(provider): add Bitbucket provider for authentication
nextauthjs/next-auth pull request #12198
Opened 2024-11-07 19:17 UTC by halvaradop

## ☕️ Reasoning
This pull request introduces a new OAuth 2.0 provider for the `Auth.js` package: Bitbucket. This integration allows users to authenticate with their `Bitbucket` accounts.

## Notes
Due to a temporary issue with the image formatting tool, the provider's image could not be uploaded at this time. The image will be added in a subsequent commit once the issue is resolved.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2025-01-05 13:40 UTC, falcowinkler approved these changes

2025-01-21 05:37 UTC, falcowinkler requested changes

2025-01-21 05:37 UTC, falcowinkler commented on docs/pages/getting-started/providers/bitbucket.mdx
> +https://example.com/auth/callback/google
all the callback urls are incorrect

2025-01-21 05:37 UTC, falcowinkler commented on docs/pages/getting-started/providers/bitbucket.mdx
> +AUTH_GOOGLE_ID
env vars names incorrect

2025-01-21 20:31 UTC, halvaradop commented on docs/pages/getting-started/providers/bitbucket.mdx
> +https://example.com/auth/callback/google
Thanks for noting my carelessness and notifying

2025-01-21 20:35 UTC, halvaradop commented on docs/pages/getting-started/providers/bitbucket.mdx
> +AUTH_GOOGLE_ID
Noooo, I had been too careless in the previous changes. 😔

2025-01-21 20:55 UTC, falcowinkler requested changes

2025-01-21 20:55 UTC, falcowinkler commented on pnpm-lock.yaml
did you mean to commit the changes to this file?
it should not be updated as part of this PR

2025-01-21 20:56 UTC, falcowinkler commented on docs/pages/getting-started/providers/bitbucket.mdx
> +AUTH_GOOGLE_ID
it happens 😌

2025-01-21 21:21 UTC, halvaradop commented
Ups, I have updated the `pnpm-lock.yaml` file and didn't want to do it

2025-01-22 00:02 UTC, balazsorban44 approved these changes

2025-01-22 00:03 UTC, merged

2025-01-22 14:24 UTC, halvaradop commented
Thanks @falcowinkler and @balazsorban44 for your help in improving this PR