fix: add oauth_token_secret to requests
nextauthjs/next-auth pull request #1322
Opened 2021-02-16 14:04 UTC by balazsorban44

**What**:

Fixing OAuth 1 flows

**Why**:

Multiple issues reported that we do not use `oauth_token_secret` as intended.
See spec: https://oauth.net/core/1.0a/

**How**:

As far as I can tell, we only checked with a single OAuth 1.0 provider (Twitter), which apparently worked by simply setting `oauth_token_secret` to `null`.

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged
      

fixes #1321 
fixes #855

2021-02-16 14:07 UTC, balazsorban44 commented
@iaincollins Would appreciate your eyes on this, as you might have a reason for dropping `oauth_token_secret` in certain places! I checked with the Twitter provider, and with these changes, it still works!

2021-02-16 16:06 UTC, aksanoble requested changes
This may lead to some breaking changes as typeorm still depends on refreshToken. Can you please check if the necessary column and tokenSecret gets added to the DB as well?

2021-02-16 19:16 UTC, balazsorban44 commented
Good catch @aksanoble! I am not good with the adapters though, so I might have to wait for help from Iain.

2021-02-20 06:01 UTC, erhankaradeniz commented
Any progress on this?

2021-02-20 07:26 UTC, aksanoble commented
> Any progress on this?

Looks like there's still work to do. In the meanwhile if you want to access oauth_token_secret just use the token available as refreshToken.

2021-02-20 09:26 UTC, erhankaradeniz commented
> > Any progress on this?
> 
> Looks like there's still work to do. In the meanwhile if you want to access oauth_token_secret just use the token available as refreshToken.

I'm not sure I'm understanding what you mean. I'm trying to combine next-auth with strapi. Followed this guide: [Authenticate with next-auth](https://strapi.io/blog/user-authentication-in-next-js-with-strapi). 

I'm seeing the refreshToken and accedToken, but when I use the accessToken or the refreshtoken to send to my backend, next-auth prompts me this error: 

```
https://next-auth.js.org/errors#oauth_callback_handler_error TypeError: Cannot read property 'id' of undefined
```

This is correct since my backend does not understand the callback with the accessToken, probably because the accessToken is not correct?

I'm sorry I do not want to hijack this PR with my issue.

2021-02-28 19:16 UTC, Cryptoking74 approved these changes
Cryptoking74 (bryanjones)(Administrator)approved

2021-02-28 19:19 UTC, Cryptoking74 approved these changes

2021-02-28 19:19 UTC, Cryptoking74 commented on src/server/lib/oauth/callback.js
> -    const tokens = await client.getOAuthAccessToken(oauthToken, null, oauthVerifier)
Cryptoking74 (bryanjones)
(Administrator) approved

2021-02-28 19:19 UTC, Cryptoking74 commented on src/server/lib/oauth/callback.js
> -    const tokens = await client.getOAuthAccessToken(oauthToken, null, oauthVerifier)
Approved

2021-02-28 20:14 UTC, huynhminhcanh commented
.github/ci-workflow.yml

2021-02-28 20:14 UTC, huynhminhcanh commented
.github/ci-workflow.yml

2021-02-28 20:14 UTC, huynhminhcanh commented
> .github/ci-workflow.yml

2021-02-28 23:06 UTC, Cryptoking74 approved these changes
Approved coin, CryptoKing💫(Bryan Jones)authorized docs.for coin

2021-02-28 23:19 UTC, Cryptoking74 commented
> .github/ci-workflow.yml

What is this?

2021-02-28 23:32 UTC, Cryptoking74 requested changes
Bryan jones

2021-03-07 23:56 UTC, balazsorban44 commented
@iaincollins I wonder if we could just also return this value with a different name IN ADDITION to the current one? This wouldn't break anything, but people using OAuth 1.0 would know what to look for?

2021-04-14 15:59 UTC, giuseppeg commented
> @iaincollins I wonder if we could just also return this value with a different name oauth_token_secret IN ADDITION to the current one (refreshToken)

@balazsorban44 I second this. I just spent one hour trying to figure out how to get the `oauth_token_secret` and eventually landed here :)

2021-04-14 19:25 UTC, balazsorban44 commented
@aksanoble as you suggested, I just also keep `refreshToken` for backward compatibility.

`oauth_token` and `oauth_token_secret` will now be available in the `account` object in both the `signIn` and `jwt` callbacks!

2021-04-14 19:26 UTC, merged