Document the additional parameters in JWT
nextauthjs/next-auth pull request #1550
Opened 2021-03-18 19:07 UTC by ifly7charlie

Expose the signingKey, and options for verification and encryption

**What**: Documentation of signingKey and options

**Why**: To make it easier to control the JWT key

**How**: Extra documentation text

**Checklist**:

- [ x ] Documentation
- [ ] Tests
- [ x ] Ready to be merged

2021-04-06 17:27 UTC, balazsorban44 requested changes
Thank you! Could you please address my small changes, and this will be good to go!

2021-04-06 17:27 UTC, balazsorban44 commented on www/docs/configuration/options.md
> +  // to authenticate indirectly (eg to a database driver)
```suggestion
  // You can generate a signing key using `jose newkey -s 512 -t oct -a HS512`
  // This gives you direct knowledge of the key used to sign the token so you can use it
  // to authenticate indirectly (eg. to a database driver)
```

2021-04-06 17:27 UTC, balazsorban44 commented on www/docs/configuration/options.md
> +  // message.
```suggestion
  // This is used to generate the actual signingKey and produces a warning
  // message if not defined explicitly.
```

2021-04-08 08:00 UTC, ifly7charlie commented
Thank you for that - it's embarrassing how wrong the text was!

2021-04-08 11:59 UTC, balazsorban44 approved these changes
@ifly7charlie thank you so much! Honest contributions are never embarrassing! Happy for your help here!

2021-04-08 12:00 UTC, merged