Update pages.md
nextauthjs/next-auth pull request #1592
Opened 2021-03-26 13:56 UTC by jayliew

Updated Credentials Sign-In code example to indicate how to use `getServerSideProps` but still also showing the older `getInitialProps` example

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

2021-03-26 15:30 UTC, balazsorban44 requested changes
Thank you! This is appreciated. Could you please do the same at other occurrences of `getInitialProps` as well?

2021-03-26 15:30 UTC, balazsorban44 commented on www/docs/configuration/pages.md
> +}
```suggestion
// This is the recommended way for Next.js 9.3 or newer
export async function getServerSideProps(context){
  return {
    props: {
      csrfToken: await getCsrfToken(context)
    }
  }
}
```

2021-03-26 17:58 UTC, jayliew commented
> Thank you! This is appreciated. Could you please do the same at other occurrences of `getInitialProps` as well?

I'll make another pull request after this one gets merged.

2021-03-26 22:02 UTC, balazsorban44 commented
@jayliew couldnyoi please do the same for the other `getInitialProps` references as well?

2021-03-28 10:02 UTC, balazsorban44 requested changes
could you please incorporate #1596?

2021-03-29 21:49 UTC, jayliew commented
@balazsorban44 How do I edit an existing PR for further modification?

2021-03-30 12:28 UTC, balazsorban44 commented
You check out the branch you worked on locally (`patch-1` in your case), and any commits pushed to it will be reflected in this PR, automatically!

2021-03-30 22:30 UTC, balazsorban44 approved these changes
Thank you! 🙂

2021-03-30 22:31 UTC, merged