feat(provider): add Mailchimp provider
nextauthjs/next-auth pull request #1781
Opened 2021-04-20 09:00 UTC by michalbundyra

**What**: add new provider - Mailchimp

**Why**: working in project where I am using this provider, so it might be useful also for others

**How**:

**Checklist**:

- [x] Documentation
- [ ] Tests N/A ?
- [x] Ready to be merged

2021-04-20 12:02 UTC, balazsorban44 requested changes
Gotta love providers that implement OAuth in a way that "just works". 😁🎉 Nice PR, had a tiny comment, could you please check?

2021-04-20 12:02 UTC, balazsorban44 commented on src/providers/mailchimp.js
> +    scope: '',
Do you really not need to set any scopes here? 🤔

2021-04-20 13:26 UTC, balazsorban44 commented on src/providers/mailchimp.js
> +export default (options) => {
```suggestion
export default Mailchimp(options) {
```

2021-04-20 18:54 UTC, balazsorban44 commented
@michalbundyra my question stands about the scope. I wasn't curious if you can remove it but rather if it really works for you locally without providing any? I assumed that you would need something as basic as openid or something like that

2021-04-22 08:23 UTC, michalbundyra commented
@balazsorban44 in my code I have empty string for scope and it works, but I'll verify it again and will be back here. Thanks

2021-04-22 13:04 UTC, balazsorban44 commented
thanks! could you please revert the src/providers/index.js file change? that file is auto-generated now

2021-04-23 07:52 UTC, michalbundyra commented
@balazsorban44 I checked again documentation and there is no single word about the scope. It works for me with empty scope tho. 

It's now rebased, so merge conflicts are resolved. Thanks

2021-04-23 10:14 UTC, balazsorban44 approved these changes
Thank you so much!

2021-04-23 10:15 UTC, merged