docs(adapters): mention new types
nextauthjs/next-auth pull request #1916
Opened 2021-05-03 13:59 UTC by lluia

## Reasoning 💡

Following #1881 mention the new **Adapter** type utilities in our documentation in:
- [Typescript](https://next-auth.js.org/getting-started/typescript)
- [Adapters](https://next-auth.js.org/schemas/adapters)

Specify the two to use them (in **TS** or through **JSDoc**).

## Checklist 🧢

- [x] Documentation
- [ ] ~Tests~
- [ ] ~Ready to be merged~
      

## Affected issues 🎟

Closes #1881

2021-05-03 16:52 UTC, ndom91 approved these changes
LGTM 👍

2021-05-03 19:38 UTC, balazsorban44 requested changes

2021-05-03 19:38 UTC, balazsorban44 commented on www/docs/getting-started/typescript.md
> +const MyAdapter: Adapter<AdapterConfig> = () => {
Per #1914 we should refer to the first generic as client, and all additional options should be passed in the second generic

2021-05-04 14:27 UTC, balazsorban44 requested changes
The adapters section slipped under the Module Augmentation part, but I think it should be top level. The useful links section is supposed to be under Module Augmentation also (it is now just the Adapters section came accidentally before it).

Maybe a few words about JSDoc and how that can be utilized for IntelliSense even without TS?

Also, should we show all the available generics of the  Adapter rather than just the first one?

2021-05-05 20:29 UTC, lluia commented
@balazsorban44 I addressed your suggestions 😄

2021-05-05 20:31 UTC, balazsorban44 requested changes
thanks @lluia, found a small typo

2021-05-05 20:31 UTC, balazsorban44 commented on www/docs/getting-started/typescript.md
> +/** @type { import("next-auth/adapters").Adapters } */
`Adapter`! 😁

2021-05-05 20:54 UTC, balazsorban44 requested changes

2021-05-05 20:54 UTC, balazsorban44 commented on www/docs/getting-started/typescript.md
> +This will work in code editors with a strong Typescript integration like VSCode or WebStorm. It might not work if you're using more lightweight editors like VIM or Atom.
TypeScript

2021-05-06 07:55 UTC, balazsorban44 requested changes
@lluia I think you misunderstood my comment. :smile: I could have been more verbose...

2021-05-06 07:55 UTC, balazsorban44 commented on www/docs/getting-started/typescript.md
> +/** @type { import("next-auth/adapters").Adapters } */
Still seeing `import("next-auth/adapters").Adapters` The interface is called `Adapter`

2021-05-06 08:08 UTC, lluia commented
@balazsorban44 hopefully now is right 🙃

2021-05-06 08:14 UTC, balazsorban44 approved these changes

2021-05-06 09:10 UTC, merged