Call user() to get user details to check in condition
nextauthjs/next-auth pull request #2046
Opened 2021-05-22 17:52 UTC by kiranvj

We were using if(user) which will be always true as `user` is a function. We need to call user() and use the return value in if condition

## Reasoning 💡

## Checklist 🧢

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## Affected issues 🎟

2021-05-23 19:49 UTC, balazsorban44 requested changes
Thanks! So if we want to clean this up a bit, I would suggest something like this:

```js
async authorize(credentials, req) {
  // You need to provide your own logic here that takes the credentials
  // submitted and returns either a object representing a user or value
  // that is false/null if the credentials are invalid.
  // e.g. return { id: 1, name: 'J Smith', email: 'jsmith@example.com' }
  // You can also use the `req` object to obtain additional parameters
  // (i.e., the request IP address) 
  const res = await fetch("/your/endpoint", {
    method: 'POST',
    body: JSON.stringify(credentials),
    headers: { "Content-Type": "application/json" }
  })
  const user = await res.json()
  
  // If no error and we have user data, return it
  if (res.ok && user) {
    return user
  }
  // Return null if user data could not be retrieved
  return null
}
```

I feel that this is a much more usual pattern. What do you think?

2021-05-24 14:27 UTC, kiranvj commented
> I feel that this is a much more usual pattern. What do you think?

I totally agree with you. The proposed pattern is more usual in the project.  I have update the code as suggested and pushed. Kindly check.

2021-05-24 14:53 UTC, balazsorban44 approved these changes

2021-05-24 14:54 UTC, merged

2021-05-24 14:55 UTC, balazsorban44 commented
Glad you agreed! Thanks for the PR