Updated DynamoDB Adaptor documentation
nextauthjs/next-auth pull request #2125
Opened 2021-06-03 16:10 UTC by manishprivet

## Reasoning 💡

The way DynamoDB was implemented in the adapters repo was changed, and the documentation needed to be updated accordingly.

## Checklist 🧢

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## Affected issues 🎟
https://github.com/nextauthjs/adapters/pull/126

2021-06-04 00:07 UTC, balazsorban44 requested changes
Please see https://github.com/nextauthjs/adapters/pull/126#pullrequestreview-675822717

2021-06-04 00:08 UTC, balazsorban44 requested changes

2021-06-04 00:08 UTC, balazsorban44 commented on www/docs/adapters/dynamodb.md
> +You need to pass `DocumentClient` from `aws-sdk` to the adapter in addition to the table name.
Maybe say that you need to pass a `DocumentClient` instance, see you construct it with the `new` keyword?

2021-06-09 12:47 UTC, balazsorban44 requested changes
Could you please match the content of this PR with https://github.com/nextauthjs/adapters/pull/126/files

2021-06-09 13:05 UTC, manishprivet commented
@balazsorban44 Apologies, it was hard to keep track of it.

2021-06-09 15:00 UTC, balazsorban44 reviewed
Thank you! :tada:

2021-06-09 15:00 UTC, balazsorban44 approved these changes

2021-06-09 15:01 UTC, merged