chore(docs): email contact update
nextauthjs/next-auth pull request #2467
Opened 2021-08-01 15:48 UTC by ndom91

## Reasoning 💡

Updated the security contact details to Balazs or my Email. 

There were a few auto fixed prettier things in these less often touched files, but primarily if you just search "yo@ndo.dev" or "info@balazsorban.com" in these changed files, you'll find the 3 points that were actually changed. 

As long as that email of yours being out there is okay with you, i'm good with mine being out there too and this should be good to go to merge :+1: 

## Checklist 🧢

- [x] Documentation
- ~[ ] Tests~
- [x] Ready to be merged

## Affected issues 🎟

2021-08-01 16:13 UTC, balazsorban44 approved these changes

2021-08-01 16:37 UTC, balazsorban44 requested changes
Let Iain still be listed and say they should send the email to all of us

2021-08-01 18:53 UTC, iaincollins commented
Thanks for doing this!

We really need to set up a role account for security submission (after we had picked a top level domain) but this is very welcome in the interim.

2021-08-02 02:29 UTC, balazsorban44 approved these changes

2021-08-02 15:18 UTC, merged