add Keycloak provider
nextauthjs/next-auth pull request #2485
Opened 2021-08-05 05:34 UTC by bbigras

## Reasoning 💡

Add a Keycloak provider.

I tested with a self-hosted Keycloak.

I based this PR on the auth0 provider.

I was first wondering if it was possible in https://github.com/nextauthjs/next-auth/pull/2411#issuecomment-892768889.

## Checklist 🧢

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## Affected issues 🎟

2021-08-05 10:26 UTC, balazsorban44 commented
Awesome, so I assume you were able to get it to work! 🎉 I will have a closer look. From now on, I will want us to enforce stricter defaults for built-in providers for consistency, and I also want to see if we can get an account on the provider platform for testing purposes before merging. But this looks promising.

2021-08-05 14:06 UTC, bbigras commented
> so I assume you were able to get it to work!

Yep, and I just tested with please-open.it.

To reproduce:

- create client with `http://localhost:3000` as the root URL
- set `Access Type` to `confidential` (the secret will be in the `credentials` tab after save)
- you can create a user, but when I tested it used mine as I was already logged.

`KEYCLOAK_ISSUER=https://app.please-open.it/auth/realms/<realm_id>`

2021-08-16 17:09 UTC, chuongxl approved these changes

2021-08-17 11:42 UTC, masone commented
Apart from testing, is there something we can do to help moving this forward?

2021-08-17 11:53 UTC, balazsorban44 commented
I'm just want to have  a look myself before merging. Just use the source code as a custom provider if you need this already. Currently busy with migrating our adapters.

2021-08-18 14:46 UTC, bbigras commented
> There is also a merge conflict. @bbigras could you address that please?

@balazsorban44 Done. It seems a rebase was enough.

2021-08-23 20:30 UTC, balazsorban44 requested changes
Awesome, finally got around to check this out! :+1: Looks good, I only had a small comment/suggestion. Other than that, it is good to go!

2021-08-23 20:30 UTC, balazsorban44 commented on src/providers/keycloak.js
> +        email: profile.email,
```suggestion
        name: profile.name ?? profile.preferred_username,
        email: profile.email,
        image: null
```

2021-08-23 20:35 UTC, bbigras commented
Done. Do you want me to squash it, or do you want to do it while merging or something?

2021-08-23 20:43 UTC, merged

2021-09-01 02:37 UTC, dicksonmelo commented
> It's merged! Give me a sec, and I'll release it too.
> 
> Here it is: `v4.0.0-next.24`

Is there any forecast when it can be used?

2021-09-01 02:39 UTC, dicksonmelo commented
> It's merged! Give me a sec, and I'll release it too.
> 
> Here it is: `v4.0.0-next.24`

@balazsorban44 
Is there any forecast when it can be used? Can I download this v4.0.0-next.24 release?

2021-09-01 07:44 UTC, balazsorban44 commented
Absolutely, `npm install next-auth@4.0.0-next.24` 😉. Make sure you don't have a caret (^) in the version number in package.json. Had a small trouble with NPM a while ago and there is a buggy 4.0.0 version out unfortunately. 😬 So you have to force the exact version above. This will be solved when we release this into stable.

2021-09-01 11:54 UTC, dicksonmelo commented
I downloaded the version, but I was trying to use it like the previous versions. Thank you so much!