WIP: feat(providers): add WeChat
nextauthjs/next-auth pull request #2519
Opened 2021-08-13 10:06 UTC by zhuangya

## Reasoning 💡
introduce WeChat OAuth 2.0 provider

## Checklist 🧢

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## Affected issues 🎟

2021-08-13 10:29 UTC, balazsorban44 requested changes
Thank you for this PR! We are close to a new major release, so I kindly ask you to change the base of this PR from `main` to `next`. Unfortunately, there is a big chance for a few merge conflicts, so the easiest way is to probably reopen this PR where you base your branch on our `next` branch to begin with. I am sorry for the inconvenience, this will hopefully not be required for long.

To comply with the new Provider API, I kindly ask you to incorporate my suggestions. I might have a few more when you have a PR against `next`, but I am happy to help you through this to be merged!

I would also like to ask, do you know how we could set up a test account on WeChat to add it to our basic sign-in test suite to ship this with more confidence?

2021-08-13 10:29 UTC, balazsorban44 commented on src/server/lib/oauth/client.js
> +    params.secret = provider.clientSecret;
Custom behavior like this won't be supported in the upcoming major release. Read #2411 and the corresponding RFC #1846 for context.

2021-08-13 10:29 UTC, balazsorban44 commented on src/server/lib/oauth/client.js
> +    }
Custom behavior like this won't be supported in the upcoming major release. Read #2411 and the corresponding RFC #1846 for context.

2021-08-13 10:29 UTC, balazsorban44 commented on src/providers/wechat.js
> +        avatar: profile.headimgurl
The upcoming version will require all built-in providers to return a unified output here by default, which is `id`, `name`, `email`, `image`, defaulting to `null`. Read #2411 and the corresponding RFC #1846 for context.

2021-08-13 10:29 UTC, balazsorban44 commented on www/docs/providers/wechat.md
> +
Please also add a Configuration section

2021-08-13 10:29 UTC, balazsorban44 commented on src/providers/wechat.js
> +    protection: "state",
```suggestion
    protection: ["state"],
```

2021-08-13 11:27 UTC, zhuangya commented
> Thank you for this PR! We are close to a new major release, so I kindly ask you to change the base of this PR from `main` to `next`. Unfortunately, there is a big chance for a few merge conflicts, so the easiest way is to probably to reopen this PR where you base your branch on our `next` branch to begin with. I am sorry for the inconvenience, this will hopefully not be required for long.
> 
> To comply with the new Provider API, I kindly ask you to incorporate my suggestions. I might have a few more when you have a PR against `next`, but I am happy to help you through this to be merged!
> 

No worry, I'll take care of this.
I've already gone through your suggestions, and I'd like to read #2411 and #1846 first.

> I would also like to ask, do you know how we could set up a test account on WeChat to add it to our basic sign-in test suite to ship this with more confidence?

not yet, but i think i can figure it out

> Feel free to ask me anything

Thank you, it's very kind of you!

2021-10-19 15:38 UTC, closed without merging

2022-08-31 01:03 UTC, jonidelv commented
I really need this 😿 is there any chance of this moving forward? Sorry, I'm not yet familiar with the code to help.

2022-10-19 15:45 UTC, StarDxxx commented
we need wechat

2022-12-27 02:38 UTC, DaZiYuan commented
Please support WeChat, WeChat is a commonly used way in China

2022-12-31 06:14 UTC, kulame commented
we need wechat., please support it !

2023-04-24 17:42 UTC, zuohuadong commented
we need wechat., please support it !

2024-01-30 17:23 UTC, sharkqwy commented
World's 18% users are on WeChat. It doesn't make sense to support all other smaller social providers while ignore it. Please add support for WeChatProvider

2024-01-31 11:25 UTC, daniel548604106 commented
Please support wechat

2024-02-12 23:29 UTC, JacobSyndeo commented
WeChat is even more important to support than one may think, as many of the other top providers (e.g. Google, Facebook, X/Twitter, Discord, etc.) are _completely blocked_ in mainland China, leaving WeChat as essentially _THE_ only viable option there.

It's not just a matter of WeChat being installed on nearly 1 billion phones… it's that it's the de-facto platform in China, which is (in a close tie for) the most populated nation in the world.

So yeah, WeChat matters. Please prioritize this.

(If it's a matter of not being able to test it, I can help test this if necessary, and I'm sure at least _some_ of the rest of the 1 billion users will help test it as well!)