fix(react): singIn provider type
nextauthjs/next-auth pull request #2655
Opened 2021-09-03 18:56 UTC by Patryks1

## Reasoning 💡

Currently the signIn provider type will only accept email and credentials. This pr will accept any string instead. 

## Checklist 🧢

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged

## Affected issues 🎟
[Fixes](https://github.com/nextauthjs/next-auth/issues/2654)

2021-09-04 09:18 UTC, balazsorban44 requested changes
Thank you for jumping on this!

Some thoughts.

Ideally I would like that whenever someone types `signIn("` in their IDE, a list of suggestions come up to show all the providers we have built-in support for. This currently includes `credentials`, `email` and any of the OAuth providers' id.

Example:
![](https://i.imgur.com/UrWDfyt.png)

Although we don't want to restrict the first param of `signIn` to these values in case someone creates a custom provider, with a unique id.

For this to work, I found the following workaround:

```ts
// https://github.com/microsoft/TypeScript/issues/29729#issuecomment-832522611
export type LiteralUnion<T extends U, U = string> =
  | T
  | (U & Record<never, never>)

export type RedirectableProviderType = "email"  |  "credentials"
export type BuiltInProviderType = LiteralUnion<RedirectableProviderType | OAuthProviderType>
```

OAuthProviderType should be a union of id strings from across our `src/providers/*` folder. We will have to generate this type, by iterating over that folder and use the file name, and put it in a file like `src/providers/oauth-types`.

2021-09-04 09:18 UTC, balazsorban44 commented on src/react/index.tsx
> +  provider?: string,
This seems to destroy the purpose of RedirectableProvider.

What we would like here is to hint the user of any of the built-in provider types, but not restricting it to those.

2021-09-05 15:05 UTC, Patryks1 commented
@balazsorban44 Any ideas on how you could possibly grab all the providers dynamically? I can only think of require.context/filesystem which might work in this scenario. however i dont think they will be done on compile which means they wont show up on intel sense. I could do it the dirty way and just add the providers by hand?

2021-09-05 15:07 UTC, balazsorban44 commented
I would use a node script to grab filenames.

For inspiration https://github.com/nextauthjs/docs/blob/main/scripts/generate-providers.js

2021-09-06 18:43 UTC, Patryks1 commented
> I would use a node script to grab filenames.
> 
> For inspiration https://github.com/nextauthjs/docs/blob/main/scripts/generate-providers.js
> 
> Then call this script when the build script is run

Nice one, Let me know if thats what you where looking for.

2021-09-06 19:49 UTC, balazsorban44 commented on package.json
> +      "/scripts"
```suggestion
      "/react.js"
```

2021-09-06 20:14 UTC, balazsorban44 requested changes
So I had some suggestions, and since I wanted to get this PR as quickly as possible, I thought I was committing to your branch, but instead, it ended up on a totally different branch...

Could you incorporate this commit with the suggested changes to your branch?: https://github.com/nextauthjs/next-auth/commit/2d8270c7668201da732db073a2a1817fe68d0355

It is mostly moving things around a bit, you have done nice work!

2021-09-07 08:15 UTC, Patryks1 commented on tsconfig.json
> +    "./scripts/*.js"
done

2021-09-07 08:15 UTC, Patryks1 commented on package.json
> +      "/scripts"
done

2021-09-07 08:56 UTC, merged