feat: TikTok provider
nextauthjs/next-auth pull request #2720
Opened 2021-09-10 16:56 UTC by denkristoffer

## Reasoning 💡

Adds TikTok provider. Their implementation is a bit funky, so there's a bit of customisation.

## Checklist 🧢

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

2021-11-16 22:47 UTC, balazsorban44 requested changes
Thank you! I added some suggestions.

Do note that we plan to release v4 to stable very soon, so it would be nice to get this merged before that.

Could you show some kind of proof of login that shows the returned `name`, `email`, `picture`, or any of those that are actually returned?

We could use that, later on, to refer to, when people are having issues.

Thank you!

2021-11-16 22:47 UTC, balazsorban44 commented on src/providers/tiktok.ts
> +          return { ...options, followRedirect: true, timeout: 99999 }
There is now a top-level option for setting timeout:

https://github.com/nextauthjs/next-auth/pull/3188

I would also suggest setting something more sensible, like 5-10 seconds.

2021-11-16 22:47 UTC, balazsorban44 commented on src/providers/tiktok.ts
> +      url: "https://open-api.tiktok.com/platform/oauth/connect/?response_type=code",
```suggestion
      url: "https://open-api.tiktok.com/platform/oauth/connect",
```

2021-11-16 22:47 UTC, balazsorban44 commented on src/providers/tiktok.ts
> +      url: "https://open-api.tiktok.com/oauth/access_token/",
```suggestion
      url: "https://open-api.tiktok.com/oauth/access_token",
```

2021-11-16 22:47 UTC, balazsorban44 commented on src/providers/tiktok.ts
> +      url: "https://open-api.tiktok.com/oauth/userinfo/",
```suggestion
      url: "https://open-api.tiktok.com/oauth/userinfo",
```

2021-11-16 22:47 UTC, balazsorban44 commented on src/providers/tiktok.ts
> +  display_name: string
Anything else that you can decipher from the returned `tikTokData` that could be useful for people here?

2021-11-25 22:29 UTC, balazsorban44 commented
Gentle bump. We will release v4 next week, if this doesn't address my comments, we cannot merge it and therefore will be closed.

2021-11-25 22:30 UTC, balazsorban44 commented
An accompanying docs page should also be added at https://github.com/nextauthjs/docs/tree/main/docs/providers

2021-11-26 08:02 UTC, denkristoffer commented
Thank you for the bump. I didn't mean to close this, I will try to get to this in time for v4. Rebasing on the `beta` branch.

2021-11-26 09:15 UTC, denkristoffer commented
> Could you show some kind of proof of login that shows the returned name, email, picture, or any of those that are actually returned?
>
> We could use that, later on, to refer to, when people are having issues.

What are you looking for here? A demo website?

2021-11-26 11:08 UTC, balazsorban44 commented
Basically just a screenshot of the returned data by the `profile` callback. Either the JSON from a `console.log` or an image from the site. Example: https://github.com/nextauthjs/next-auth/pull/2848#issue-1008276523

2021-11-26 11:10 UTC, balazsorban44 commented on src/providers/tiktok.ts
> +        }
I think I'll update the `httpOptions` to expose `followRedirect` as well, so we hopefully can get rid of the `openid-client` `custom` import.

2021-11-26 22:41 UTC, balazsorban44 commented
If you merge `beta` into your branch now, https://github.com/nextauthjs/next-auth/pull/3287 exposes the `httpOptions`, so you can get rid of the above-mentioned import.

2021-11-27 00:17 UTC, balazsorban44 commented
I've tried to register an App, it had some caveats, that should be mentioned in the docs.

Would be appreciated if you opened a PR regarding this https://github.com/nextauthjs/next-auth/pull/2720#issuecomment-979500400

First of all, it seems like you cannot use `http`. even for local development. Second, my app registration has to go through a seemingly manual review process.

2021-11-27 08:31 UTC, denkristoffer commented
Great! Docs PR is under way 🙂

2021-11-27 10:55 UTC, balazsorban44 commented
In that case, could you paste in the logged in result just so I (and future everyone) knows that this provider should work?

2021-11-28 08:26 UTC, denkristoffer commented
I don't currently have a site using this provider, but I'll try to run it with the demo website later today.

2021-11-28 09:43 UTC, balazsorban44 commented
I don't expect an actual site. do try with the demo app. otherwise how did you even create the PR? 😀

2021-11-30 08:15 UTC, denkristoffer commented
> I don't expect an actual site. do try with the demo app. otherwise how did you even create the PR? 😀

I created this for a personal project, but eventually decided against using TikTok for auth since their oauth implementation honestly seemed to change quickly.

I couldn't get the demosite working with the provider yesterday because of the oauth client complaining about an "Invalid URL". I will debug and try again tonight, hopefully.

2021-11-30 10:47 UTC, balazsorban44 commented
Unfortunately, if we cannot show proof of login, I will have to close this PR. I'll check back at the end of my day, and if works then, we can merge. Otherwise, I'll close this for now. We can revisit the idea at a later time after v4 has landed in stable.

Thank you for your contribution nonetheless.

2021-11-30 17:59 UTC, closed without merging

2022-08-09 05:28 UTC, Oxicode commented
anything news??