Added authentik provider
nextauthjs/next-auth pull request #3625
Opened 2022-01-13 21:15 UTC by Pacerino

## Reasoning 💡
I've added [Authentik](https://goauthentik.io/) as a provider

## Checklist 🧢
The provider has been added as a `.ts` file, The Documentation about this provider will be added as a PR to the docs repo.

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

The provider can be merged as soon its reviewed. I've deployed a local setup and checked if the Login/Logout works as intended.

2022-01-17 00:35 UTC, balazsorban44 requested changes
Thank you, this looks great! Left only a small suggestion.


Also, could you paste in an image of sorts that shows you that the login was successful with the name email profile picture? We use it as proof for future reference. :pray:

2022-01-17 00:35 UTC, balazsorban44 commented on src/providers/authentik.ts
> +    idToken: true,
```suggestion
```

This should not be necessary anymore. We detect if `openid` is added as a scope instead.

2022-01-18 10:12 UTC, Pacerino commented
I've removed the `idToken`.
Here is a gif as a proof of the working login.
![pv0a6](https://user-images.githubusercontent.com/22194063/149916997-be2dcfc2-d968-4195-a0d9-0f73193c14ed.gif)

2022-01-19 00:37 UTC, balazsorban44 approved these changes

2022-01-19 00:37 UTC, balazsorban44 commented
Thank you!

2022-01-19 00:38 UTC, merged