chore: add v4 migration script for adapters
nextauthjs/next-auth pull request #3874
Opened 2022-02-07 16:41 UTC by ndom91

## Reasoning 💡

Initial attempt at some DB migration scripts in the `v4 upgrade` docs. For migrating adapters created under v3 to the new v4 schema.

## Checklist 🧢

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## Affected issues 🎟

2022-02-07 18:10 UTC, balazsorban44 commented on packages/docs/docs/getting-started/upgrade-to-v4.md
> +ADD COLUMN "oauth_token" varchar(191) NOT NULL
So these are only needed if they are using Twitter OAuth 1.0. We should comment and link to the docs. Otherwise these can be dropped.

2022-02-07 18:10 UTC, balazsorban44 commented on packages/docs/docs/getting-started/upgrade-to-v4.md
> +DROP COLUMN "updated_at"
Let's comment that these have never been necessary for NextAuth.js to work, hence they are dropped, but can be kept if they want to.

2022-02-07 18:11 UTC, balazsorban44 commented on packages/docs/docs/getting-started/upgrade-to-v4.md
> +DROP COLUMN "updated_at"
Same as https://github.com/nextauthjs/next-auth/pull/3874/files#r800927573

2022-02-07 18:11 UTC, balazsorban44 commented on packages/docs/docs/getting-started/upgrade-to-v4.md
> +DROP COLUMN "updated_at"
https://github.com/nextauthjs/next-auth/pull/3874/files#r800927573

2022-02-07 18:11 UTC, balazsorban44 commented on packages/docs/docs/getting-started/upgrade-to-v4.md
> +DROP COLUMN "updated_at"
https://github.com/nextauthjs/next-auth/pull/3874/files#r800927573

2022-02-07 18:11 UTC, balazsorban44 requested changes
Only commented on the MySQL one, but should be the same for Postgres

2022-02-07 18:15 UTC, TheoBr commented
Looks good overall, really appreciate the separate examples for MySQL and Postgres 

Two concerns:
- “Rename” isn’t an option for a lot of sharded dbs [like Planetscale](https://github.com/planetscale/beta/discussions/122)
- by making multiple new fields non nullable, you're likely breaking any existing entries in those tables

2022-02-07 18:43 UTC, ndom91 commented
Thanks for the feedback everyone! I've addressed the comments so far. 

Regarding `RENAME` not working with sharded DBs like planetscale, I think that basically rules out using an automated migration like this, right. In cases like those, if the user wants to upgrade from v3 -> v4, they'll have to manually adjust the DB if possible or potentially just create a new one and move the data over. I know that sucks, but I don't see another option if `RENAME` isn't available. 

What do yall think?

2022-02-07 20:54 UTC, TheoBr commented
```
  type               String   @map("providerType")
  refresh_token      String?  @map("refreshToken") @db.Text
  provider           String   @map("providerId")
```
^ is the fix we're using at Ping for now

2022-02-07 21:11 UTC, ndom91 commented
Yeah just remap the names in Prisma. Makes sense. For those using prisma this seems like a nice workaround, will keep it in mind!

2022-02-07 22:03 UTC, TheoBr commented
My other concern was w/ the non-nullable bindings to `expires_at` and `session_state`. Neither seem to be used, this screenshot is from a minimal production app on nextauthjs v4

![image](https://user-images.githubusercontent.com/6751787/152879594-790d2bc0-5f45-410d-b466-331601d9f047.png)

2022-02-08 10:12 UTC, ndom91 commented
@TheoBr yeah I changed those to no longer be non-nullable, sticking to the previous implementation. New v4 setups can keep the non-nullable variants going forward, but for migrations you're right - that would probably break some current implementations :+1: 

Or do you mean to allow NULL on `created_at` + `updated_at` ?

2022-02-15 00:00 UTC, balazsorban44 approved these changes
LGTM :heavy_check_mark:

2022-02-15 00:00 UTC, merged