chore(docs): update securing pages tutorial
nextauthjs/next-auth pull request #3982
Opened 2022-02-15 20:07 UTC by ndom91

## Reasoning 💡

Draft PR to address #3973 and update some tutorials and other documentation to bring `getServerSession` and `middleware` related documentation up to speed.

## Checklist 🧢

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## Affected issues 🎟

2022-02-16 09:47 UTC, lluia commented on docs/docs/tutorials/securing-pages-and-api-routes.md
> +This new `withAuth` middleware client only supports the `"jwt"` [session strategy](https://next-auth.js.org/configuration/options#session) at the moment.
```suggestion
For the time being, the `withAuth` middleware only supports `"jwt"` as [session strategy](https://next-auth.js.org/configuration/options#session).
```

2022-02-16 12:39 UTC, balazsorban44 commented on apps/dev/pages/api/examples/protected.js
> +import { getServerSession } from "next-auth/react"
import { getServerSession } from "next-auth/next"

2022-02-16 12:40 UTC, balazsorban44 commented on apps/dev/pages/api/examples/protected.js
> +  const session = await getServerSession({ req })
`const session = await getServerSession({ req, res }, options)`

And we have to decide where options come from.

2022-02-16 12:41 UTC, balazsorban44 commented on apps/dev/pages/server.js
> +        This page uses the universal <strong>getServerSession()</strong> method
`getServerSession` is not universal, it's server-only. Basically:

Before:
 - getSession: client, server

After:
 - getSession: client
 - getServerSession: server

2022-02-16 12:43 UTC, balazsorban44 commented on docs/docs/getting-started/client.md
>  - Server Side: **Yes**
This should be changed to No

2022-02-16 12:44 UTC, balazsorban44 commented on docs/docs/getting-started/client.md
> +
- Client Side: **No**
- Server Side: **Yes**

2022-02-16 17:54 UTC, ndom91 commented
@balazsorban44 okay I think your comments have been addressed here. The last thing thats open afaik is deciding where the `options` arg comes from, as you mentioned. Right?

2022-03-12 17:02 UTC, ndom91 commented
Alright I've updated this PR to remove the `getServerSession` section I'd added to the `client.md` docs page in favor of @ThangHuuVu's awesome PR which adds this (https://github.com/nextauthjs/next-auth/pull/4116). 

This one should be good to go then unless any other changes should be made.

2022-03-13 08:41 UTC, lluia approved these changes
Good from my side 💚

2022-03-13 08:49 UTC, ThangHuuVu commented
- I'd suggest revisit this after we finish the API change here: https://github.com/nextauthjs/next-auth/pull/4116 🤔

2022-03-14 18:27 UTC, lluia commented
@ThangHuuVu, I agree 👍🏽; I think both PRs should be merged simultaneously, actually. As this one is updating all the references of server-side`getSession()` to `getServerSession()` and yours is adding the docs for `getServerSession()`.

I'll review your PR as well and hopefully, we can move this forward 🍵

2022-03-15 03:37 UTC, ThangHuuVu commented
> @ThangHuuVu, I agree 👍🏽; I think both PRs should be merged simultaneously, actually. As this one is updating all the references of server-side`getSession()` to `getServerSession()` and yours is adding the docs for `getServerSession()`.
> 
> I'll review your PR as well and hopefully, we can move this forward 🍵

Sounds good, @lluia! In my PR, I changed the API of `getServerSesison` a bit to match with the API of the default `NextAuth` handler as @balazsorban44 suggested. It would affect the docs/example changes in this PR as well

2022-03-15 20:11 UTC, ndom91 commented
Yeah im up for whatever, feel free to merge this if yall wanna time it together :+1:

2022-05-31 04:07 UTC, kfranqueiro commented
As someone currently looking at upgrading an app from next-auth v3 to v4 who was very confused by things failing until stumbling across https://github.com/nextauthjs/next-auth/issues/4075, and subsequently very confused that this is not documented, evidently due to this PR being in limbo for over 3 months... is there a reason it hasn't been merged and is now in danger of being closed as stale?

2022-06-10 22:57 UTC, kfranqueiro commented
Not sure why stalebot closed this when I commented on it? Does that not count as activity?

`getServerSession` is not mentioned at all in the docs currently on the site. This PR looked like it would address that. The fact that this was opened 5 months ago, never merged, and now closed seems like a big problem. How are people actually managing to use v4 successfully if the docs are this behind?

2022-06-13 08:47 UTC, ndom91 commented
Not sure why stalebot closed this as well. Theres some overlap between this and https://github.com/nextauthjs/next-auth/pull/4116 PR. No excuse as to why it hasn't been merged yet though, `getServerSession` should probably be officially mentioned in the docs at this point :see_no_evil:

2022-06-23 10:16 UTC, balazsorban44 requested changes
Now that #4116 is merged, could we get this PR up to date? :pray:

2022-06-23 10:23 UTC, ndom91 commented
> Now that #4116 is merged, could we get this PR up to date? :pray:

Yup, was just wondering if I should still do this one or what. Will update it shortly 👍

2022-06-23 19:31 UTC, ndom91 commented
@balazsorban44 @ThangHuuVu alright this one is finally updated with `unstable_getServerSession` as well :tada: 

Anything else that you guys would like updated here? Or good to go?

2022-06-24 05:40 UTC, ThangHuuVu requested changes
@ndom91 `unstable_getServerSession` now accepts 3 arguments so I suggest the changes accordingly; please add the import for `authOptions` in the example/code as well. This is what I and @balazsorban44 came up with attempting to make this function looks similar to `NextAuthNextHandler`. 💡

2022-06-24 07:39 UTC, ndom91 commented
@ThangHuuVu great call with the arguments, I didnt realize that at first and was stuck for a minute during my upgrade to `4.6.1` in a sideproject of mine as well :joy:

Appreciate all the recommended diffs btw!

Also updated the text a bit in the SSR recommendation page based on your feedback :+1:

2022-06-24 07:49 UTC, ThangHuuVu approved these changes
Yeah, great work, PR looks ready to be merged now!

2022-06-24 07:51 UTC, LOGOLFGODORD commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->Great !! nice work team ! Always there !! yeeeeeee Sent from Mail for Windows From: Thang VuSent: Friday, June 24, 2022 3:50 AMTo: nextauthjs/next-authCc: SubscribedSubject: Re: [nextauthjs/next-auth] chore(docs): update securing pages tutorial (PR ***@***.*** approved this pull request.Yeah, great work, PR looks ready to be merged now!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 

2022-06-24 08:02 UTC, merged