chore(docs): add full stack course (Next.js/NextAuth.js/Supabase/Prisma)
nextauthjs/next-auth pull request #4086
Opened 2022-02-28 18:30 UTC by gdangelo

## Reasoning 💡

Adding a new resource to the documentation website. It is a free online course created by me and teaches about building a full-stack app with Next.js. Of course, the authentication part is implemented using NextAuth.js 😉

## Checklist 🧢

- [x ] Documentation
- ~[ ] Tests~
- [ x] Ready to be merged

## Affected issues 🎟

2022-03-01 00:41 UTC, balazsorban44 requested changes, later dismissed
Thanks! I'll review the course, but first, could we tone down the item in the list a bit? :sweat_smile: 

![image](https://user-images.githubusercontent.com/18369201/156082850-b30b5fd4-974c-44d7-a86c-770fe6761df7.png)


https://next-auth-git-fork-gdangelo-patch-1-nextauthjs.vercel.app/tutorials

2022-03-01 00:42 UTC, balazsorban44 commented on docs/docs/tutorials.md
> +### [[FREE COURSE] Build a FullStack App with Next.js, Supabase & Prisma](https://themodern.dev/courses/build-a-fullstack-app-with-nextjs-supabase-and-prisma-322389284337222224)
```suggestion
### Build a FullStack App with Next.js, NextAuth.js, Supabase & Prisma](https://themodern.dev/courses/build-a-fullstack-app-with-nextjs-supabase-and-prisma-322389284337222224)
```

2022-03-01 00:44 UTC, balazsorban44 commented
Could you give me access to the course, or at least the source code if available somewhere? :pray:

2022-03-01 07:36 UTC, gdangelo commented
> Could you give me access to the course, or at least the source code if available somewhere? 🙏

Hey Balázs, 

Thanks for your feedback. You can access the course from [here](https://themodern.dev/courses/build-a-fullstack-app-with-nextjs-supabase-and-prisma-322389284337222224) and just click **Enroll now**. It's totally free. You have to log in first, though.

2022-03-01 18:35 UTC, balazsorban44 commented
:facepalm::sweat_smile: It did not occur to me that I could just enroll since it's free... Thanks, I'll check it out. :+1:

2022-03-22 22:19 UTC, ndom91 commented
@gdangelo we'd be happy to include the course in our list, but can you please adjust it to match the formatting of all other resources in the page? I.e. no giant banner image or `[FREE COURSE]` prefix? Thanks!

2022-03-23 07:45 UTC, gdangelo commented
> @gdangelo we'd be happy to include the course in our list, but can you please adjust it to match the formatting of all other resources in the page? I.e. no giant banner image or `[FREE COURSE]` prefix? Thanks!

Thanks for your feedback. I've adjusted the formatting of this new entry to comply with all the other resources.

Please let me know if there is anything else I should do.

2022-03-23 18:50 UTC, merged