Document tunnel option for development
nextauthjs/next-auth pull request #4163
Opened 2022-03-11 23:34 UTC by breyed

Using a tunnel to set up development can be quicker and easier than hostname and certification modification if you don't need to run spend a lot of time on authentication.

## Checklist 🧢

- [x] Documentation
~[ ] Tests~
- [x] Ready to be merged

2022-03-12 18:27 UTC, ndom91 requested changes
Some small wording feedback, but generally I like the addition. Using ngrok, or a similar tunneling service, would make setting up Apple OAuth locally much easier. Thanks!

2022-03-12 18:27 UTC, ndom91 commented on docs/docs/providers/apple.md
> +One developemnt option to avoid using HTTP or localhost is to access your site through a tunnel such as [ngrok](https://ngrok.com/).
```suggestion
You can use a tunneling service like [ngrok](https://ngrok.com/) to simplify local development and easily get an HTTPS URL required for Apple OAuth settings.
```

2022-03-12 18:27 UTC, ndom91 commented on docs/docs/providers/apple.md
> +1. Follow the instructions to set up the tunnel and install the agent.
```suggestion
1. Follow the [instructions](https://ngrok.com/download) to set up an ngrok tunnel.
```

2022-03-12 18:27 UTC, ndom91 commented on docs/docs/providers/apple.md
> +An altnerative approach is to make your development computer see itself as a non-local website. Edit your host file and point your site to `127.0.0.1`.
```suggestion
An alternative approach is to setup a hostname and SSL certificates for your local computer. 

Begin by editing your host file (`/etc/hosts`) and point your site to `127.0.0.1`. For example, by adding the line: `127.0.0.1 mysite.com`
```

2022-03-12 19:31 UTC, breyed commented
After creating this PR, I discovered vercel/next.js#10935 which covers dives deeper into the HTTPS options. In summary:
* [Custom server](https://github.com/vercel/next.js/discussions/10935#discussioncomment-584332) - A variation of what's in NextAuth Apple docs now. A related note: For a newcomer, the existing NextAuth docs can be confusing and cause errors (it was for me, anyway). For the line to add to /etc/hosts, the sudo command resulted in a permission denied error (I'm using macOS). (It was easy to work around with `sudo vi`.) More importantly, what's happening with the custom server and its implications isn't clear to the uninitiated.
* [Reverse proxy](https://github.com/vercel/next.js/discussions/10935#discussioncomment-2236301) - This option seems easy but comes with deprecationa and security warnings.

It's worth considering all the options in crafting curated guidance for the NextAuth docs.

2022-03-22 22:07 UTC, ndom91 commented
If you want to develop your next.js app locally with HTTPS I highly recommend you go the reverse proxy route. i.e. generate a cert locally and set it up with nginx or caddy or something similar. This however obviously involves a bit of sys admin type work and if you're not familiar with it, your recommended solution of simply firing up an ngrok tunnel is much much easier.

Working with a custom next.js server and adding https just for local development isn't worth the headache imo. Just generate a cert, add the file paths to an nginx config and point that nginx host to `localhost:3000`, or wherever your normal dev URL is.

I think overall developing with HTTPS is a rather niche requirement. The only thing I can think of really requiring this is something like what you documented - if an OAuth provider or other 3rd party service requires it, or some of the newer web API's which only work over HTTPS like web bluetooth, geolocation, etc. none of which are related to the core NextAuth.js feature's afaik.

2022-06-10 20:36 UTC, closed without merging