fix: dropbox provider (#3899)
nextauthjs/next-auth pull request #4286
Opened 2022-03-29 21:44 UTC by kirjahylly

## Reasoning 💡

This change should fix the currently broken Dropbox provider. Dropbox userinfo endpoint uses POST, not GET, which causes the 404 error mentioned in issue #3899.

## Checklist 🧢

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## Affected issues 🎟

Fixes #3899

2022-03-31 15:09 UTC, balazsorban44 requested changes
I would rather use https://github.com/panva/node-openid-client/blob/main/docs/README.md#clientuserinfoaccesstoken-options

2022-04-09 10:53 UTC, lluia commented
@balazsorban44 I think we need to pass the provider options to invocation of `client.userinfo`:
https://github.com/nextauthjs/next-auth/blob/a72f1b6d21da89b4223542006c865862635c027b/packages/next-auth/src/core/lib/oauth/callback.ts#L135-L139
so that on the provider we can just do:
```ts
```

2022-04-09 10:55 UTC, lluia commented
Sorry, didn't mean to close it 😅

2022-06-18 15:46 UTC, closed without merging

2023-07-20 16:59 UTC, wrong7 commented
Dropbox provider still not working

2024-09-07 14:27 UTC, Kematia commented
I tested this manually and it works correctly (atleast for the login and redirect), is there any chance we can get this merged? I'm willing to pick this up, maybe I can implement the suggestion from @ubbe-xyz  😄 

cc @balazsorban44