docs: fix Custom Client Session Handling example
nextauthjs/next-auth pull request #4310
Opened 2022-04-03 04:26 UTC by reconbot

## Reasoning 💡

It made reference to a `useEffect` call that was no longer needed or present.

## Checklist 🧢

- [x] Documentation
- ~[ ] Tests~
- [ ] Ready to be merged

2022-04-03 16:27 UTC, lluia requested changes
Thanks 💚 ; just small formatting on the comment 👍🏽

2022-04-03 16:27 UTC, lluia commented on docs/docs/getting-started/client.md
> +  // with required:true status can only be loading or authenticated
```suggestion
  // if `{ required: true }` is supplied, `status` can only be "loading" or "authenticated"
```

2022-04-04 06:38 UTC, productdevbook approved these changes

2022-04-04 20:11 UTC, ndom91 approved these changes
LGTM :+1:

2022-04-04 20:11 UTC, merged