Added Notion provider
nextauthjs/next-auth pull request #4324
Opened 2022-04-04 15:57 UTC by JannisHajda

## Reasoning 💡

## Checklist 🧢

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## Affected issues 🎟

2022-04-06 15:28 UTC, 0ubbe requested changes
Thanks 💚 ; some suggestions and questions 💬

2022-04-06 15:28 UTC, lluia commented on packages/next-auth/src/providers/notion.js
> +    return {
We're trying to remove plain JS from our codebase and move everything to TS (both for security and improved DX). 

I re-wrote this file in TS:
```ts
import { TokenSetParameters } from "openid-client"
import type { OAuthConfig, OAuthUserConfig } from "."

interface NotionTokenSet extends TokenSetParameters {
  owner?: {
    user: {
      id: string
    }
  }
}

interface NotionTokenSetParams {
  tokens: NotionTokenSet
}

export interface NotionProfile extends Record<string, any> {
  id: string
  name: string
  avatar_url: string
  person: {
    email: string
  }
}

export interface NotionProviderOptions {
  notionVersion: string
}

export default function Notion<P extends NotionProfile>(
  options: OAuthUserConfig<P> & NotionProviderOptions
): OAuthConfig<P> {
  return {
    id: "notion",
    name: "Notion",
    type: "oauth",
    authorization: {
      url: "https://api.notion.com/v1/oauth/authorize",
      params: {
        owner: "user",
      },
    },
    token: "https://api.notion.com/v1/oauth/token",
    userinfo: {
      request: async ({ tokens }: NotionTokenSetParams) => {
        const { access_token = "" } = tokens

        if (!access_token) {
          throw new Error("Notion Provider: No access token received")
        }

        const res = await fetch(
          "https://api.notion.com/v1/users/" + tokens.owner?.user.id,
          {
            headers: {
              Accept: "application/json",
              "Content-Type": "application/json",
              "Notion-Version": options.notionVersion || "2022-02-22",
              Authorization: "Bearer " + access_token,
            },
          }
        )

        if (!res.ok) {
          throw new Error("Something went wrong while trying to get the user")
        }

        const result = await res.json()
        return result
      },
    },
    profile: (profile) => ({
      id: profile.id,
      name: profile.name,
      email: profile.person.email,
      image: profile.avatar_url,
    }),
    ...options,
  }
}
```
Can you commit this instead?

I see **Notion** doesn't seem to have a **Well Known** endpoint 🙄 ( cc. @balazsorban44 ), but the options can be much simplified as per my example.

Note that internally we use `OpenID-client` to handle the OAuth callback for us, and this already uses **Basic Auth** for the token endpoint. However, I see we call it supplying a user ID `tokens.owner?.user.id` 🤔 

Could you try simplifying it even further with just:
```ts
import { TokenSetParameters } from "openid-client"
import type { OAuthConfig, OAuthUserConfig } from "."

export interface NotionProfile extends Record<string, any> {
  id: string
  name: string
  avatar_url: string
  person: {
    email: string
  }
}

export interface NotionProviderOptions {
  notionVersion: string
}

export default function Notion<P extends NotionProfile>(
  options: OAuthUserConfig<P> & NotionProviderOptions
): OAuthConfig<P> {
  return {
    id: "notion",
    name: "Notion",
    type: "oauth",
    authorization: {
      url: "https://api.notion.com/v1/oauth/authorize",
      params: {
        owner: "user",
      },
    },
    token: "https://api.notion.com/v1/oauth/token",
    userinfo: "https://api.notion.com/v1/users",
    profile: (profile) => ({
      id: profile.id,
      name: profile.name,
      email: profile.person.email,
      image: profile.avatar_url,
    }),
    ...options,
  }
}
```
and see if it works? 🤞🏽

2022-04-06 15:28 UTC, lluia commented on docs/docs/providers/notion.md
> +    clientSecret: process.env.NOTION_CLIENT_SECRET
We should add `notionVersion` here as it's an extra option that can be customised.

2022-04-07 18:29 UTC, ndom91 commented on packages/next-auth/src/providers/notion.js
> +        notionVersion = "2022-02-22"
Looks like starting middle of last year, they require this `notion-version` header on all API requests. ([Source](https://developers.notion.com/changelog/unversioned-requests-no-longer-accepted)).

`2022-02-22` is just the latest version at the time of writing ([Source](https://developers.notion.com/changelog/releasing-notion-version-2022-02-22)). 

This version probably shouldn't ever change unless they change something about how they do authentication or the userinfo endpoint.

2022-04-09 10:46 UTC, lluia commented on packages/next-auth/src/providers/notion.js
> +        notionVersion = "2022-02-22"
I see, so maybe let's expose it as a customisation option to prevent confusion? 💭

2022-04-09 20:17 UTC, ndom91 commented on packages/next-auth/src/providers/notion.js
> +        notionVersion = "2022-02-22"
What I"m trying to say is, if they change `notionVersion`, they'll probably break the API unknowingly. 

I think the `notionVersion` should actually be hidden away from the user and hard-coding it to this working version of the API here is fine imo. Unless I misunderstood something about their versioning, or maybe you're thinking behind exposing it to the user?

2022-04-10 09:48 UTC, lluia commented on packages/next-auth/src/providers/notion.js
> +        notionVersion = "2022-02-22"
Yep, my bad as I wrote `"let's expose"` when I meant `"let's not expose"` 😂 ; let's hide it 👍🏽

2022-04-10 10:29 UTC, ndom91 commented on packages/next-auth/src/providers/notion.js
> +        notionVersion = "2022-02-22"
Hahah okay great

2022-07-02 03:53 UTC, closed without merging

2022-07-03 11:20 UTC, ndom91 commented
@JannisHajda are you still interesting in getting this over the finish line? 

If so, we can reopen it. I think there are still some open points from @lluia's review, like refactoring it to TS