chore(docs): Fixes refresh token example
nextauthjs/next-auth pull request #4849
Opened 2022-07-06 03:54 UTC by jakehewitt

## ☕️ Reasoning

What changes are being made? What feature/bug is being fixed here?

- On initial login `account.expires_at` is a timestamp and shouldn't be added to Date.now(). 
- When refreshing the token `refreshedTokens.expires_at` is undefined. It should be using `refreshedTokens.expires_in`

## 🧢 Checklist

- [X] Documentation
- [ ] Tests
- [X] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: No open issues

Related to: https://github.com/nextauthjs/next-auth/pull/4540

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2022-07-08 22:58 UTC, lucalves approved these changes

2022-07-12 10:45 UTC, balazsorban44 requested changes
Thanks, looks like this was a small oversight on our part. I added a small comment to use `expires_in` explicitly since `expires_at` is just a calculated value by the underlying lib we use and not guaranteed to exist in the future.

2022-11-08 14:50 UTC, gusliedke commented on docs/docs/tutorials/refresh-token-rotation.md
> +          accessTokenExpires: account.expires_at * 1000,
Hi @balazsorban44 I'm not sure we have `expires_in` property in **account** anymore hence the need to remove `Date.now()` from the example and use `expires_at` instead. Can we confirm that? Right now the documentation is wrong and if you follow it,  `accessTokenExpires` will never expire breaking anyone's code.

2022-12-01 14:54 UTC, railson-ferreira approved these changes
I've tested it, works properly with my IdentityServer

2022-12-12 09:36 UTC, ndom91 commented on docs/docs/tutorials/refresh-token-rotation.md
> +          accessTokenExpires: account.expires_at * 1000,
Why would we need to change it to `expires_at`? I dont see that being set anywhere in next-auth and providers themselves should be settings `expires_in` according to the spec Balazs linked?

2022-12-29 13:52 UTC, vwatel commented
Any updates on this one?
We are currently looking at using this library, which looks very solid and clean. We miss the refresh token rotation at the moment to have it fully integrated with the library.

2023-02-10 01:13 UTC, balazsorban44 commented
This documentation has been rewritten at: https://authjs.dev/guides/basics/refresh-token-rotation

The related issue about `expires_in` vs `expires_at` is tracked here #6538

2023-02-10 01:13 UTC, closed without merging