Add vanilla Postgres adapter for NextAuth using the pg package.
nextauthjs/next-auth pull request #4933
Opened 2022-07-14 12:32 UTC by jakecoppinger

This is my first contribution to this repo - please let me know if there are things I'm missing/could improve!

All tests are passing.

## ☕️ Reasoning

What changes are being made? What feature/bug is being fixed here?

## 🧢 Checklist

- [ x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: https://github.com/nextauthjs/next-auth/issues/4897

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2022-07-14 18:43 UTC, davidmfoley commented on packages/adapter-postgres/README.md
> +  adapter: PostrgesAdapter(client)
typo (`Postrges`)

2022-07-17 12:19 UTC, jakecoppinger commented
I'm still unable to solve a bug - `createSession` being called with an `undefined` `userId`: https://github.com/nextauthjs/next-auth/issues/4897

I initially thought I fixed it, but the issue persists. Are you able to reproduce and suggest a fix? :)

2022-07-19 21:54 UTC, balazsorban44 commented
Just remembered, could you add the adapter to these lists:

For auto-labeling issues:
https://github.com/nextauthjs/next-auth/blob/main/.github/issue-labeler.yml
https://github.com/nextauthjs/next-auth/blame/main/.github/ISSUE_TEMPLATE/3_bug_adapter.yml#L23-L34

For auto-labeling PRs
https://github.com/nextauthjs/next-auth/blob/main/.github/pr-labeler.yml

2022-07-19 22:04 UTC, balazsorban44 commented
What do you think about calling it `@next-auth/pg-adapter`? :slightly_smiling_face:

2022-07-20 07:45 UTC, jakecoppinger commented
Renamed to `@next-auth/pg-adapter` and updated the files you mentioned :) 
I'm still stuck on this issue, any ideas? https://github.com/nextauthjs/next-auth/pull/4933#issuecomment-1186500481

2022-07-21 15:25 UTC, balazsorban44 commented
@jakecoppinger could you update the lock file so we can run tests in GitHub actions? (just run `pnpm install` and commit the result)

2022-11-15 06:25 UTC, craig-bowers commented
Thanks for sharing your Postgres adapter! I used this as a starting point to set up NextAuth with [pg-promise](https://github.com/vitaly-t/pg-promise) instead of pg and JavaScript instead of TS.

I am running into an issue though. When I use your adapter and try signing into my Google account via [Google Provider](https://next-auth.js.org/providers/google) I'm getting a new database entry into each of my users, accounts, and sessions tables, but the next-auth.session-token cookie is not getting set when I'm redirected back to http://localhost:3000 and when I try using useSession() on the front-end the status says I'm unauthenticated.

When I bypass the adapter it lets me log in just fine and I can use useSession() to see my Google email, image, etc., and it tells me that I'm authenticated. Obviously none of the data makes its way into Postgres with it bypassed though.
` // adapter: PostgresAdapter(db),`

Any idea on what the problem might be? I can share my [...nextauth].js or adapter file if you think it'll help.

2022-12-05 09:43 UTC, jakecoppinger commented
@craig-bowers I haven't done any testing with anything but a standard email and password unfortunately, so no ideas on my end.

I'm still stuck on an issue (#4897), did you find a way to fix that by any chance?!

2023-02-02 14:19 UTC, bonesoul commented
found a fix now?

2023-02-23 08:49 UTC, bonesoul commented
LF this to get merged.

2023-02-24 05:31 UTC, jakecoppinger commented
I tried to fix my PR based on the suggestion in this comment, but I'm not having any success unfortunately: https://github.com/nextauthjs/next-auth/issues/4897#issuecomment-1363414338

`getSessionAndUser` doesn't appear to be called. I've added logging in a test project to see what gets returned from the function but it isn't being called.

Any debugging help would be appreciated!

2023-02-24 05:48 UTC, jakecoppinger commented
Fixed! Needed to return `id` (using SQL command `RETURNING`) when creating a new user.

2023-02-24 05:49 UTC, jakecoppinger commented
Oops, meant to close the issue and not the PR.

Issue is now fixed. Rebased and ready for review & merge!

2023-02-27 23:34 UTC, bonesoul commented
eager now to get this merged :)

2023-05-22 22:56 UTC, LFCavalcanti commented
Hi,

Any update to merge this PR?

2023-06-16 15:01 UTC, robahtou commented
Any updates on this? Happy to help get this through the finish line!

2023-08-28 05:22 UTC, ThangHuuVu commented on packages/adapter-pg/src/index.ts
> +        "userId" = $2, expires = $3
we don't need to update userId since it's never passed to this function from core.

2023-08-28 05:23 UTC, ThangHuuVu requested changes
hi folks, sorry for the delay - I reviewed the PR, it looks good to me - I added a small comment. To get this PR merged, here are a couple of left-overs that we need to address:
1. Publish it as ESM-only and under `@auth/` namespace. Make sure to have correct `package.json` file and `tsconfig.json` file
2. Add documentation as JSDoc. 
3. Rebase & passing tests

You can take reference from other adapters like Kysely, Drizzle, Prisma etc.

cc @jakecoppinger @robahtou let me know if you have any questions!

2023-09-22 07:49 UTC, ThangHuuVu commented
hi folks, I finished this PR in https://github.com/nextauthjs/next-auth/pull/8679, so I'm closing this one - thanks everyone!

2023-09-22 07:49 UTC, closed without merging