feat: Add Todoist provider
nextauthjs/next-auth pull request #5253
Opened 2022-08-30 18:49 UTC by elpnt

## ☕️ Reasoning

Adds [Todoist](https://todoist.com/home) to the available providers.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

## 🎥 Demo video

Run `pnpm dev:app` and it works fine

https://user-images.githubusercontent.com/39664774/187518215-c67c4816-ee78-4ab8-8042-21fc4cb72248.mp4

2022-10-20 16:11 UTC, ThangHuuVu requested changes

2022-10-20 16:11 UTC, ThangHuuVu commented on packages/next-auth/src/providers/todoist.ts
> +    },
Can you try the client option: `client_secret_post`? 
You won't need to do the request here, `openid-client` will take the option and do it for you
```
    token: "https://todoist.com/oauth/access_token",
    client: {
      token_endpoint_auth_method: "client_secret_post",
    },
```

2022-10-22 07:47 UTC, elpnt commented
I rewrote the token fetch process and it works fine. I also removed unused field type definitions from `TodoistProfile`

2022-10-23 06:54 UTC, ThangHuuVu commented
Thanks for sending this @elpnt 🙌, could you add the provider to the list in `2_bug_provider.yml`? That's the last required change in this PR!

2022-10-23 08:44 UTC, ThangHuuVu approved these changes
LGTM!

2022-10-23 10:16 UTC, merged