Update upstash-redis.md
nextauthjs/next-auth pull request #5261
Opened 2022-08-31 15:30 UTC by Itsnotaka

## ☕️ Reasoning

What changes are being made? What feature/bug is being fixed here?
The doc was outdated and the code written within the docs are incorrect at the time of writing this.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2022-08-31 17:33 UTC, lluia requested changes
Thanks 💚

Small formatting issue.

2022-08-31 17:33 UTC, lluia commented on docs/docs/adapters/upstash-redis.md
> +});
```suggestion
const redis = new Redis({
  url:  process.env.UPSTASH_REDIS_URL,
  token:  process.env.UPSTASH_REDIS_TOKEN
});
```

2022-09-01 11:02 UTC, balazsorban44 commented on docs/docs/adapters/upstash-redis.md
> +import { Redis } from "@upstash/redis";
```suggestion
import { Redis } from "@upstash/redis"
```

2022-09-01 11:02 UTC, balazsorban44 commented on docs/docs/adapters/upstash-redis.md
> +});
```suggestion
})
```

2022-09-01 11:03 UTC, balazsorban44 commented on docs/docs/adapters/upstash-redis.md
> +  token:  process.env.UPSTASH_REDIS_TOKEN
```suggestion
  url: process.env.UPSTASH_REDIS_URL,
  token: process.env.UPSTASH_REDIS_TOKEN
```

2022-09-01 11:03 UTC, balazsorban44 approved these changes
Thanks!

2022-09-01 11:03 UTC, merged