fix: added providing database name in options
nextauthjs/next-auth pull request #5290
Opened 2022-09-05 16:59 UTC by AVStarikovich

## ☕️ Reasoning

Providing database name is important, because, by default it is "test", and if you use another name in your application, you can't get user data without additional code.

## 🧢 Checklist

- [+] Documentation
- [x] Tests (not needed)
- [+] Ready to be merged

## 🎫 Affected issues
Fixes: https://github.com/nextauthjs/next-auth/issues/5289

## 📌 Resources

- [Contributing guidelines](./CONTRIBUTING.md)
- [Code of conduct](./CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2022-09-06 14:55 UTC, ndom91 commented on packages/adapter-mongodb/README.md
> +    dataBaseName: 'my-data-base-name'
nit: `databaseName`

2022-09-07 15:54 UTC, balazsorban44 requested changes

2022-09-07 15:54 UTC, balazsorban44 commented on packages/adapter-mongodb/README.md
> +    dataBaseName: 'my-data-base-name'
```suggestion
    databaseName: 'my-data-base-name'
```

2022-09-07 15:54 UTC, balazsorban44 commented on packages/adapter-mongodb/src/index.ts
> +  dataBaseName?: string
```suggestion
  databaseName?: string
```

2022-09-07 15:54 UTC, balazsorban44 commented on packages/adapter-mongodb/src/index.ts
> +    const _db = (await client).db(options.dataBaseName)
```suggestion
    const _db = (await client).db(options.databaseName)
```

2022-09-07 15:55 UTC, balazsorban44 approved these changes
Thanks!

2022-09-07 15:56 UTC, merged