chore(docs): update documentation `callbacks` to include user Id as example
nextauthjs/next-auth pull request #5465
Opened 2022-10-01 12:34 UTC by ArkShocer

## ☕️ Reasoning

Some people (including me) have been asking on how to add the userId to the client session. I think changing the documentation a bit to include the id would probably help a lot of people.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

2022-10-01 14:55 UTC, balazsorban44 requested changes
I don't think this is the correct way to document this without explaining why it is not exposed by default. See https://github.com/nextauthjs/next-auth/issues/4903

2022-10-02 19:42 UTC, ArkShocer commented
Notes on why the user id is not exposed by default is already documented in the `session` section. Are the latest changes in the correct direction or would it maybe make sense to move this to the faq since it's frequently asked?

2022-10-03 14:01 UTC, balazsorban44 commented on docs/docs/configuration/callbacks.md
> +The contents _user_, _account_, _profile_ and _isNewUser_ will vary depending on the provider and on if you are using a database or not. You can persist data such as User ID, OAuth Access Token in th
```suggestion
The contents _user_, _account_, _profile_ and _isNewUser_ will vary depending on the provider and if you are using a database. You can persist data such as User ID, OAuth Access Token in this token, see the example below for `access_token` and `user.id`. To expose it on the client side, check out the [`session()` callback](#session-callback) as well.
```

2022-10-03 14:02 UTC, balazsorban44 commented on docs/docs/configuration/callbacks.md
> +The session callback is called whenever a session is checked. By default, **only a subset of the token is returned for increased security**. If you want to make something available you added to the t
```suggestion
The session callback is called whenever a session is checked. By default, **only a subset of the token is returned for increased security**. If you want to make something available you added to the token (like `access_token` and `user.id` from above) via the `jwt()` callback, you have to explicitly forward it here to make it available to the client.
```

2022-10-03 14:02 UTC, balazsorban44 approved these changes
Thank you!

2022-10-03 14:03 UTC, merged