feat: ZITADEL provider
nextauthjs/next-auth pull request #5479
Opened 2022-10-03 14:25 UTC by peintnermax

## ☕️ Reasoning

Add [ZITADEL](https://zitadel.com) OIDC provider

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2022-10-05 20:32 UTC, balazsorban44 commented on packages/next-auth/src/providers/zitadel.ts
> +      }
```suggestion
      return {
        id: profile.sub,
        name: profile.name,
        email: profile.email,
        image: profile.picture,
      }
```

2022-10-05 21:08 UTC, balazsorban44 commented on packages/next-auth/src/providers/zitadel.ts
> +    },
```suggestion
```

From the docs: https://docs.zitadel.com/docs/apis/openidoauth/endpoints it does not sound like this is actually necessary. Can we just use the default,

2022-10-05 21:09 UTC, balazsorban44 requested changes
Thanks, added some suggestions

2022-10-05 21:22 UTC, peintnermax commented
Thanks! Applied and tested your suggestions 👍

2022-10-06 07:44 UTC, balazsorban44 approved these changes

2022-10-06 07:44 UTC, merged