feat(adapters): add Hasura adapter
nextauthjs/next-auth pull request #5707
Opened 2022-11-01 22:14 UTC by arjunyel

## ☕️ Reasoning

Adding a Hasura adapter. The Hasura team is willing to maintain

## 🧢 Checklist

- [X] Documentation
- [X] Tests
- [X] Ready to be merged

2022-11-14 22:33 UTC, arjunyel commented
Hi friends, anything you need from me to land this? A lot of the code is auto-generated and tree shaken when you build :)

2022-12-19 14:56 UTC, balazsorban44 commented
Hi, just wanted to give a note, this is interesting for us, just haven't had the time to look into it yet! :bow:

> "The Hasura team is willing to maintain"

:green_heart:

2023-06-30 18:15 UTC, azlekov commented
What is the plan here? Any timeframe when the Hasura adapter will be official?

2023-09-13 12:53 UTC, ThangHuuVu commented
hi @arjunyel , I pushed some commits to format the PR. 

- [x] Publish it as ESM-only and under @auth/ namespace. Make sure to have correct package.json file and tsconfig.json file
- [x] Add documentation as JSDoc.

To get this PR merged, could you help with the build errors? Sorry, I am still not very familiar yet with Hasura & GraphQL so I didn't touch the code in `src/`.
 I'm curious about the files that you added in the PR. Could you walk me through all the files? I am guessing that we don't need the `gql` and `hasura` directories, but not sure 🤔. Thanks for the PR & sorry for the delay, let's get this done!

2023-09-19 17:00 UTC, arjunyel commented
@ThangHuuVu Fixed build error and cleaned up.

We need the `hasura` directory in order to run the tests against a Hasura instance. `gql` directory has been renamed to `lib` and is the output of GraphQL Codegen, basically it's a generated SDK for accessing Hasura.

Btw I am no longer on the Hasura team so I am not sure of their support plans of this. Thanks for all your help friend!

2023-09-20 02:29 UTC, ThangHuuVu commented
> Btw I am no longer on the Hasura team so I am not sure of their support plans of this. Thanks for all your help friend!

🫶 

> We need the `hasura` directory in order to run the tests against a Hasura instance. `gql` directory has been renamed to `lib` and is the output of GraphQL Codegen, basically it's a generated SDK for accessing Hasura.

Thanks for the explanation - if we need to ship the codegen output as part of the library, let's run the script before running `tsc`?

2023-09-20 02:38 UTC, ThangHuuVu requested changes

2023-09-20 02:38 UTC, ThangHuuVu commented on packages/adapter-hasura/src/index.ts
> +import { log } from "console"
unused import, let's remove

2023-09-20 02:38 UTC, ThangHuuVu commented on packages/adapter-hasura/src/index.ts
> + *1. [Track all the tables and relationships in Hasura](https://hasura.io/docs/latest/schema/postgres/using-existing-database/#step-1-track-tablesviews)
Let's write this as a Info block:
:::info
Tips: [Track all the tables and relationships in Hasura](https://hasura.io/docs/latest/schema/postgres/using-existing-database/#step-1-track-tablesviews)
:::

2023-09-20 02:38 UTC, ThangHuuVu commented on packages/adapter-hasura/src/index.ts
> + *   ```
Let's remove this part, we already have a installation section above

2023-10-02 19:14 UTC, arjunyel commented
@ThangHuuVu addressed feedback and moved codegen to a build script

2023-10-04 01:59 UTC, ThangHuuVu approved these changes

2023-10-04 02:05 UTC, ThangHuuVu commented
@arjunyel could you help check the build error, I wonder if we really need docker for code gen? 🤔

2023-10-04 16:50 UTC, arjunyel commented
@ThangHuuVu sorry for all the trouble! Removed Docker from the build step, replaced it by having the GraphQL Schema as a file in the repo. I need the schema for the codegen so its either run a docker container or have the schema in a GraphQL file. Thank you for all the help!

2023-10-07 01:47 UTC, merged