Update nextjs.md
nextauthjs/next-auth pull request #5917
Opened 2022-11-28 19:43 UTC by dominikzaczek

Fixed a typo in the documentation

> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](../Security.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](../Security.md)
- [Contributing guidelines](../CONTRIBUTING.md)
- [Code of conduct](../CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2022-11-28 22:01 UTC, ndom91 approved these changes
Good catch! Thanks ❤️

2022-11-28 22:02 UTC, ndom91 requested changes
Another small typo

2022-11-28 22:02 UTC, ndom91 commented on docs/docs/configuration/nextjs.md
> +Currently, the underlying Next.js `cookies()` method [only provides read access](https://beta.nextjs.org/docs/api-reference/cookies) to the request cookies. This means that the `expires` value is str
```suggestion
Currently, the underlying Next.js `cookies()` method [only provides read access](https://beta.nextjs.org/docs/api-reference/cookies) to the requested cookies. This means that the `expires` value is stripped away from `session` in Server Components. Furthermore, there is a hard expiry on sessions, after which the user will be required to sign in again. (The default expiry is 30 days).
```

2023-03-29 03:52 UTC, balazsorban44 commented
This seems to be fixed already: https://next-auth.js.org/configuration/nextjs

2023-03-29 03:52 UTC, closed without merging