feat(core): allow clearing cookies from `jwt()`
nextauthjs/next-auth pull request #6337
Opened 2023-01-09 09:43 UTC by iMrDJAi

## ☕️ Reasoning
Currently there is no way to invalidate session from the `jwt()` callback. This change allows clearing the user cookies when `jwt()` returns ~~a falsy value~~ null.

~~Also, a new provider option has been added, `decodeJWT`, which allows passing the existing token of a user (if any) instead of the default one to the `jwt()` callback after provider's `authorize()`. This allows creating providers for the purpose of checking and invalidating existing user sessions.~~

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues
Fixes: https://github.com/nextauthjs/next-auth/discussions/6325

2023-01-09 12:40 UTC, balazsorban44 requested changes
Few comments:

- This should be done against https://github.com/nextauthjs/next-auth/tree/main/packages/core as `next-auth` only receives critical fixes at this point
- Let's allow returning `null` in `jwt` which indicates that we should call `sessionStore.clean()`.
- Looks like you did changes to the `session` callback too, but I don't understand the reason. Could we revert that?

2023-01-09 12:41 UTC, balazsorban44 commented on packages/next-auth/src/core/routes/callback.ts
> +  const decodedToken = useJwtSession && decodeJWT
Why is this necessary?

2023-01-09 12:43 UTC, balazsorban44 commented on packages/next-auth/src/core/types.ts
> +export type Falsy = null|undefined|false
Let's not introduce a new type for this, only check for `null`. The other values don't make sense anyway.

2023-01-09 12:44 UTC, balazsorban44 commented on packages/next-auth/src/core/routes/callback.ts
> +    decodeJWT,
Unclear what this tries to accomplish. Could you clarify?

2023-01-09 12:45 UTC, balazsorban44 commented on packages/next-auth/src/core/types.ts
>     * This callback is called whenever a JSON Web Token is created (i.e. at sign in)
The comment above needs to be extended that explains, returning `null` will invalidate the JWT session.

2023-01-09 12:45 UTC, balazsorban44 commented on packages/next-auth/src/core/types.ts
> +  }) => Awaitable<Session|Falsy>
Not sure why this is necessary

2023-01-09 17:53 UTC, iMrDJAi commented
@balazsorban44 Hello, sorry for the delay, working on the changes that you have requested.

Regarding the session callback, clearing the cookies could be done when fetching the session, not sure what else to return from it when the token is ~~falsy~~ `null`:

https://github.com/iMrDJAi/next-auth/blob/27dc1b20c0fa6c0d0e3c15f099ef27d8a132159e/packages/next-auth/src/core/routes/session.ts#L63-L68

Does setting the `response.body` to `undefined` does the job? Or should we avoid calling it at all in this case? What do you think?

Regarding the new option `decodeJWT` (or it could be `decodeExistingJWT`, it certainly needs a clearer name), the point is, if the auth cookies exist while the user is attempting to call a provider, it allows to decode the JWT of that user:

https://github.com/iMrDJAi/next-auth/blob/27dc1b20c0fa6c0d0e3c15f099ef27d8a132159e/packages/next-auth/src/core/routes/callback.ts#L41-L46

Then passing it to `jwt()` instead of `defaultToken`:

https://github.com/iMrDJAi/next-auth/blob/27dc1b20c0fa6c0d0e3c15f099ef27d8a132159e/packages/next-auth/src/core/routes/callback.ts#L41-L46

In this way, we could for example make a provider to sign out users, as we have their pervious state.

2023-01-09 22:38 UTC, balazsorban44 commented
So basically passing the previous token if I understand correctly. That should be a different PR. Could we split it please and simplify this PR?

2023-01-09 22:54 UTC, iMrDJAi commented
@balazsorban44 Alright! one thing left:

> The comment above needs to be extended that explains, returning null will invalidate the JWT session.

Working on it...

2023-01-09 23:28 UTC, iMrDJAi commented
@balazsorban44 Before creating a new PR, what should we call that option?

2023-01-09 23:31 UTC, balazsorban44 commented
don't think it should be an option, just give it as `prevToken` or `currentToken`. 🤔

BTW this will resolve #3946

2023-01-10 00:03 UTC, rolanday commented
Just curious regarding ...

> "This should be done against https://github.com/nextauthjs/next-auth/tree/main/packages/core as next-auth only receives critical fixes at this point"

What exactly does "at this point" mean? Is next-auth end-of-life?

2023-01-10 11:35 UTC, iMrDJAi commented
@rolanday Auth.js will replace NextAuth.js.

@balazsorban44 Actually that's a very good idea, we can pass both pervious and new tokens! I'll play with it a little bit then I'll create a PR.

2023-01-10 12:08 UTC, balazsorban44 commented on packages/core/src/types.ts
> +   * unauthoried access.
```suggestion
   * unauthorized access.
```

2023-01-10 12:08 UTC, balazsorban44 approved these changes
Thanks!

2023-01-10 12:11 UTC, balazsorban44 commented
@rolanday https://github.com/nextauthjs/next-auth/pull/6132#issue-1505602450

2023-01-10 12:11 UTC, merged