docs: fix typos
nextauthjs/next-auth pull request #6701
Opened 2023-02-12 13:40 UTC by Lioness100

> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

Fixed a few random typos (this was a trial run for [a CLI I made](https://github.com/Lioness100/rspell))

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

2023-02-12 16:55 UTC, balazsorban44 requested changes
Could you revert anything in https://github.com/nextauthjs/next-auth/tree/main/packages/next-auth as that's being released from the `v4` branch now? The rest looks good!

2023-02-12 17:01 UTC, Lioness100 commented
Done!

2023-02-13 12:50 UTC, balazsorban44 approved these changes

2023-02-13 12:51 UTC, merged

2023-02-13 12:52 UTC, balazsorban44 commented
Thank you!