Add Silver Sponsors to the README
nextauthjs/next-auth pull request #6757
Opened 2023-02-19 18:56 UTC by Will5

## ☕️ Reasoning

This pull request adds 🥈 Silver Financial Sponsors to README 🎉

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

## 📌 Resources

2023-02-21 15:52 UTC, ThangHuuVu requested changes

2023-02-21 15:52 UTC, ThangHuuVu commented on packages/next-auth/README.md
> +        <a href="https://vercel.com" target="_blank">
This should link to Beyond Identity

2023-02-21 15:52 UTC, ThangHuuVu commented on packages/next-auth/README.md
> +        <a href="https://vercel.com" target="_blank">
This should link to Stytch

2023-02-21 19:40 UTC, Will5 commented on packages/next-auth/README.md
> +        <a href="https://vercel.com" target="_blank">
Good catch! Thanks!

2023-02-21 19:40 UTC, Will5 commented on packages/next-auth/README.md
> +        <a href="https://vercel.com" target="_blank">
Good catch! Thanks!

2023-02-23 02:48 UTC, ThangHuuVu approved these changes

2023-02-23 02:49 UTC, ThangHuuVu commented
@Will5 LGTM, please update the branch before we merge 🙌 I'm not sure why I can't update your PR on GitHub UI, normally I can do that by myself 😅

2023-02-23 04:32 UTC, merged