Add Whop to available providers
nextauthjs/next-auth pull request #6872
Opened 2023-03-03 23:58 UTC by jacc

## ☕️ Reasoning

Whop is an online platform where users can buy digital goods and services like Notion templates, Discord communities, web apps, and more - our goal is to make the process of buying digital products easier, faster, and more secure for everyone. By adding Whop's API to Auth.js, it will allow our users to integrate our API into their Next.js-based products in a seamless manner.

## 🧢 Checklist

- [] Write provider
- [] Test provider
- [] Write documentation

2023-03-06 15:57 UTC, stevo2105 approved these changes

2023-03-06 15:57 UTC, stevo2105 commented on docs/docs/reference/05-oauth-providers/whop.md
> +## Example
Add the Vercel template here!

https://vercel.com/templates/next.js/whop-template

2023-03-14 13:56 UTC, Wyatt-SG approved these changes

2023-03-24 14:46 UTC, jacc commented
Hey there, wanted to bump this @ThangHuuVu

2023-05-03 08:30 UTC, ThangHuuVu requested changes
Hi there, thanks for sending the PR! We have some items to address before merging this:
- [ ] Migrating to JSDoc (Please take `packages/core/src/provider/github.ts` as an example) & copy the code change to `packages/core/src/provider/whop.ts` - This will make the provider available in `next-auth` `v5`
- [ ] Add a demo recording to show that the integration has success!
- [ ] Add the provider name to `.github/ISSUE_TEMPLATE/2_bug_provider.yml`

Let me know if you have any questions!

2023-05-20 17:05 UTC, closed without merging