Chen/patch 2
nextauthjs/next-auth pull request #7726
Opened 2023-06-04 02:36 UTC by HiChen404

## ☕️ Reasoning

Refactor Tencent QQ Provider with TypeScript.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged

## 🎫 Affected issues

[Add Tencent QQ Provider](https://github.com/nextauthjs/next-auth/pull/4354)

Because I do not have permission to continue to commit, I opened a new PR.

2023-06-05 16:33 UTC, balazsorban44 requested changes
Please move this to https://github.com/nextauthjs/next-auth/tree/main/packages/core/src/providers

(Check out any provider there for instructions on formatting)

2023-06-06 01:54 UTC, HiChen404 commented
I modified the commit, please take a look. 

Thanks for taking the time to maintain this project. :D

2023-07-09 15:27 UTC, Tian-que commented
Good job! Thank you for doing this

2023-07-09 15:43 UTC, ThangHuuVu requested changes
Thanks for the PR, I left some comments. Could you also add an entry of the provider at `.github/ISSUE_TEMPLATE/2_bug_provider.yml`? 🙏

2023-07-09 15:43 UTC, ThangHuuVu commented on packages/core/src/providers/qq.ts
> + *      clientSecret: process.env.TENCENT_APP_KEY,
```suggestion
 *      clientSecret: process.env.TENCENT_SECRET,
```

2023-07-09 15:43 UTC, ThangHuuVu commented on packages/core/src/providers/qq.ts
> +            method: "GET",
since the default is `GET`, we can remove this options

2023-07-09 15:43 UTC, ThangHuuVu commented on packages/core/src/providers/qq.ts
> +            method: "GET",
since the default is `GET`, we can remove this options

2024-03-27 02:13 UTC, yiyungent commented
@Tian-que 
Thank you very much. Considering the Chinese market, QQ login is absolutely necessary ! ! !

2024-09-12 08:11 UTC, closed without merging