feat(providers): add Ory Hydra provider
nextauthjs/next-auth pull request #7755
Opened 2023-06-07 09:11 UTC by tomcastro

> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

Adding Ory Hydra as an OAuth2 provider for logging in.

## 🧢 Checklist

- [x] Documentation
- [x] Tests
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2023-09-18 20:11 UTC, vinckr commented
Hello reviewers,
anything I can do to move this PR forward? 
Would love to add an official example with NextAuth to our documentation!

2023-09-20 13:19 UTC, ThangHuuVu requested changes

2023-09-20 13:19 UTC, ThangHuuVu commented on packages/next-auth/provider-logos/ory-dark.svg
please help remove this file, it's not needed 🙏

2023-09-20 13:19 UTC, ThangHuuVu commented on packages/next-auth/provider-logos/ory.svg
please help remove this file, it's not needed 🙏

2023-09-20 13:19 UTC, ThangHuuVu commented on packages/core/src/providers/ory-hydra.ts
> +    type: "oauth",
We can put this provider as `oidc` type. Then, we can remove the `wellKnown` options below, as its automatically added by `next-auth` core.

2023-09-20 13:19 UTC, ThangHuuVu commented on packages/core/src/providers/ory-hydra.ts
> +        id: profile.sub,
why only return id? we normally return name, email and picture, too.

2023-12-29 03:13 UTC, ndom91 commented
@tomcastro hey if you'd still like this to be merged can you please remove the `next-auth/provider-logos/*` files as well as take a look at the merge conflicts and remove the `pnpm-lock.yaml` changes? Thanks!

2024-01-25 15:47 UTC, merged