fix(ts): add overloads to withAuth middleware
nextauthjs/next-auth pull request #7999
Opened 2023-07-10 06:19 UTC by rexfordessilfie

## ☕️ Reasoning

The `withAuth` middleware returns different values depending on provided arguments. In the current implementation it returns a union such as:`NextMiddlewareWithAuth | NextMiddlewareResult | ...`.

This union is type is not narrow enough for use in scenarios where we expect a callable `NextMiddlewareWithAuth` that we can invoke later after getting some outside context from the middleware `request` object. 

In summary, when we want to do something like this:
```ts
export default middleware(req: Request, event: NextFetchEvent){
   // ...do something with Request
   const response = withAuth({...})(req, event)  // OR withAuth(req, {...})
   // ...do something with Response?
  return response
}
```

**Solution**: This PR adds type overloads such that the types narrow down as expected depending on the arguments supplied to `withAuth`. This lets us do the above without any type issues.

## 🧢 Checklist

- [x] Documentation (N/A)
- [x] Tests (N/A)
- [x] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: https://github.com/nextauthjs/next-auth/issues/7997

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2023-07-10 20:09 UTC, balazsorban44 commented
Thanks, could you open this against the `v4` branch? 🙏

2023-07-10 20:24 UTC, rexfordessilfie commented
Thanks! Will do.

2023-07-10 20:38 UTC, rexfordessilfie commented
Done, @balazsorban44 ✅. Let me know if I did everything right!

2023-07-11 16:27 UTC, ThangHuuVu requested changes
Thanks for the detailed bug report and the PR, @rexfordessilfie 🙏 I left a comment, let me know what you think!

2023-07-11 17:29 UTC, rexfordessilfie commented on packages/next-auth/src/next/middleware.ts
> +) => ReturnType<NextMiddlewareWithAuth>
Thanks for the feedback! Yes, you are right. It was a copy directly from `NextMiddlewareWithAuth`.

I did not consider using `req: NextRequestWithAuth` directly. I noticed I was getting type errors when it was `req: Request` and so I made a generic version of `NextMiddlewareWithAuth` to fix the type errors!

I will switch to this and request a re-review!

2023-07-12 03:36 UTC, ThangHuuVu approved these changes
LGTM!

2023-07-12 03:49 UTC, merged