feat: Improve Prisma Adapter
nextauthjs/next-auth pull request #821
Opened 2020-11-02 07:54 UTC by williamluke4

2021-01-02 01:12 UTC, BjoernRave commented
what is blocking from this getting merged?

2021-01-02 01:48 UTC, balazsorban44 commented
Hi @BjoernRave, first of all there are some merge conflicts that must be fixed before merge. Also, someone from the core team should review this. I am unfortunately only familiar with the database less flows, so it is waiting for someone else.

I for one cannot even decide if this is a breaking change, or not.

2021-01-21 11:14 UTC, williamluke4 commented
@balazsorban44 Merge conflicts have been resolved

2021-01-21 12:05 UTC, balazsorban44 requested changes
Any way of making the two new dependencies optional? I don't think these should be downloaded for those who do not use the Prisma Adapter at all.

We recently opened up a repository for new adapters at https://github.com/nextauthjs/adapters

I am wondering if this `PrismaNew` could be the first official adapter there, leading the way for the community with a good example. 🙂

We plan to separate out adapters and not adding more to the core anyway, exactly because of the additional packages they bring to users who do not need them, and we wish them to be maintainable directly by the community.

As of now, we have TypeORM and Prisma built-in, and even when we move these to another place, they can be re-imported into the core to not cause any breaking change from the user perspective.

It would just be easier to maintain, I think.

2021-01-21 12:05 UTC, balazsorban44 commented on package.json
> +    "jwt-decode": "^2.2.0",
`jwt-decode` has been removed, in favor of `jsonwebtoken`, it should be removed here as well.

2021-01-21 14:35 UTC, williamluke4 commented
@balazsorban44 I'll have a chat with the team internally then I'll get back to you

2021-01-25 14:25 UTC, williamluke4 commented
Closing as work on this has moved to https://github.com/nextauthjs/adapters/pull/1

2021-01-25 14:25 UTC, closed without merging