updated example.md, added example for next app router
nextauthjs/next-auth pull request #8227
Opened 2023-08-03 19:33 UTC by s0h311

> _NOTE_:
>
> - It's a good idea to open an issue first to discuss potential changes.
> - Please make sure that you are _NOT_ opening a PR to fix a potential security vulnerability. Instead, please follow the [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md) to disclose the issue to us confidentially.

## ☕️ Reasoning

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Please [scout and link issues](https://github.com/nextauthjs/next-auth/issues) that might be solved by this PR.

Fixes: INSERT_ISSUE_LINK_HERE

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2023-08-27 14:10 UTC, ThangHuuVu requested changes
Great attempt, but I think this is a bit trivial to have in the doc 🤔 I would prefer to have one link to the [Next.js doc](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required) and one sentence like:
> Note: SessionProvider requires a client component and cannot be set inside the root layout. For more details, see [the Next.js doc]

How do you think?

2023-09-09 10:21 UTC, s0h311 commented
> Great attempt, but I think this is a bit trivial to have in the doc 🤔 I would prefer to have one link to the [Next.js doc](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required) and one sentence like:
> 
> > Note: SessionProvider requires a client component and cannot be set inside the root layout. For more details, see [the Next.js doc]
> 
> How do you think?

Sorry for my late response. I like your idea better. But I also think that it should be obvious that this is a way how you can do it with the Next.js App Router. So I propose: 

> Info: If you are using the Next.js App Router plase note that the SessionProvider requires a client component and cannot be set inside the root layout. For more details, see [the Next.js doc]

2023-09-15 04:38 UTC, ThangHuuVu commented
SGTM, go for it @s0h311

2023-09-20 06:27 UTC, ThangHuuVu commented on docs/docs/getting-started/example.md
> +If you are using the Next.js App Router plase note that the SessionProvider requires a client component and therefore cannot be set inside the root layout. For more details, check out the [Next.js do
```suggestion
If you are using the Next.js App Router, please note that the `<SessionProvider />` requires a client component and therefore cannot be put inside the root layout. For more details, check out the [Next.js documentation](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts).
```

2023-09-20 06:37 UTC, ThangHuuVu commented on docs/docs/getting-started/example.md
> +If you are using the Next.js App Router, please note that the `<SessionProvider />` requires a client component and therefore cannot be put inside the root layout. For more details, check out the [Ne
```suggestion
If you are using the Next.js App Router, please note that `<SessionProvider />` requires a client component and therefore cannot be put inside the root layout. For more details, check out the [Next.js documentation](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts).
```

2023-09-20 06:38 UTC, ThangHuuVu commented on docs/docs/getting-started/example.md
>  :::
```suggestion
:::tip
Check out the [client documentation](/getting-started/client) to see how you can improve the user experience and page performance by using the NextAuth.js client.
If you are using the Next.js App Router, please note that `<SessionProvider />` requires a client component and therefore cannot be put inside the root layout. For more details, check out the [Next.js documentation](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts).
:::
```

2023-09-20 06:46 UTC, merged