fix: Build account object with tokens spread as lowest priority
nextauthjs/next-auth pull request #8599
Opened 2023-09-15 05:14 UTC by etrepum

## ☕️ Reasoning

tokens comes from the provider and could have arbitrary keys, but type, provider, and providerAccountId have reserved meanings to NextAuth that must take priority for correct operation.

I discovered this because I had a tokens endpoint that had a type key in the response, which caused next-auth to fail because it was expecting type to be "oauth". I managed to work around it for now by mutating tokens in the profile callback.

I don't believe that this is a security issue but there's always some chance when untrusted input ends up in the wrong place.

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

I didn't find any associated issues and implementing the very small PR was easier than reporting it separately.

2023-09-15 08:06 UTC, mayank1513 approved these changes
Good catch!

2023-09-15 08:12 UTC, ThangHuuVu requested changes

2023-09-15 08:12 UTC, ThangHuuVu commented on packages/next-auth/src/core/lib/oauth/callback.ts
Please revert change in this file, as it is not needed.

2023-09-15 13:55 UTC, etrepum commented on packages/next-auth/src/core/lib/oauth/callback.ts
It’s the same bug somewhere else, to be discovered later, is there a reason not to?

2023-09-15 14:55 UTC, etrepum commented on packages/next-auth/src/core/lib/oauth/callback.ts
I've reverted the change to that file.

2023-09-16 04:34 UTC, ThangHuuVu commented on packages/next-auth/src/core/lib/oauth/callback.ts
hi @etrepum sorry for not being clear, I meant that the code in `packages/next-auth` on the main branch is not actually published anywhere. we maintain the package in the `v4` branch. For `v5`,  we are working on it at #7443 . Hope it's clear now!

2023-09-19 13:57 UTC, balazsorban44 approved these changes

2023-09-19 13:57 UTC, merged