fix: update references table
nextauthjs/next-auth pull request #9567
Opened 2024-01-07 01:14 UTC by ndom91

## ☕️ Reasoning

- References updates to general integrations 

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

 

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2024-01-07 01:15 UTC, ndom91 commented
@balazsorban44 what do you think? Should it stay as `/references`?

2024-01-07 14:48 UTC, balazsorban44 commented on docs/docs/reference/index.md
> +| `@builder.io/qwik-auth`| Community package.
let's link to it

2024-01-09 11:48 UTC, balazsorban44 requested changes

2024-01-09 11:48 UTC, balazsorban44 commented on docs/docs/reference/index.md
> +## Integrations
Need to update the link here:

https://github.com/nextauthjs/next-auth/blob/05bf014603bd8cc1f648b46771482d94ed7fd8c8/docs/docs/getting-started/introduction.mdx#L24

2024-01-09 11:48 UTC, balazsorban44 commented on docs/docs/reference/index.md
> +Here are the _state_ of planned and released packages under the `@auth/*` and `@next-auth/*` scope, as well as `next-auth`. It also includes community created and maintained packages. Packages listed
```suggestion
Here are the _state_ of planned and released integrations under the `@auth/*` and `@next-auth/*` scope, as well as `next-auth`. It also includes community created and maintained integrations. Integrations listed as "Planned" are something we'd love help with! See the [help needed](#help-needed) section below.
```

2024-01-09 11:50 UTC, balazsorban44 approved these changes

2024-01-09 11:50 UTC, merged