feat: support advanced initialization in v5
nextauthjs/next-auth pull request #9638
Opened 2024-01-14 14:37 UTC by ThangHuuVu

## ☕️ Reasoning

Add support for advanced initialization for v5. 

## 🧢 Checklist

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

## 🎫 Affected issues

Fixes: #9455 

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2024-01-16 20:11 UTC, balazsorban44 requested changes

2024-01-16 20:11 UTC, balazsorban44 commented on packages/next-auth/src/index.tsx
> + * This is useful if you want to customize the configuration based on the request, for example, to add a different provider based on the request URL's `searchParams`.
```suggestion
 * This is useful if you want to customize the configuration based on the request, for example, to add a different provider in staging/dev environments.
```

2024-01-16 20:11 UTC, balazsorban44 commented on packages/next-auth/src/index.tsx
> +import { NextRequest } from "next/server"
```suggestion
import type { NextRequest } from "next/server"
```

2024-01-16 20:14 UTC, balazsorban44 approved these changes

2024-01-16 20:14 UTC, merged

2024-05-10 19:31 UTC, chrisivo commented
Is there any way lazy initialisation can be executed asynchronously? I need to make async calls to obtain the Id's and secrets for the providers. I could do this using v4, but seems like there's no support in v5 beta (so far)?

2024-05-16 13:50 UTC, ndom91 commented
@chrisivo what do you mean exactly? The first argument to `NextAuth()` can be an async function. So yuo can do this (as is shown in most examples):

```ts
export const { auth, signIn, signOut } = NextAuth({
  providers: [ ... ],
  debug: true
})
```

But yuo can also do this:

```ts
export const { auth, signIn, signOut } = NextAuth(async (req) => {
  return {
    providers: [ ... ],
    debug: true
  }
))
```

2024-05-19 06:13 UTC, chrisivo commented
Thanks for the response ndom91. Is there any roadmap at all for introducing asynchronous functions when initialising in `next-auth` ?

2024-06-23 01:12 UTC, maiconcarraro commented
Facing same situation from @chrisivo, need to generate secret for apple sign in during initialization :(

2024-07-10 14:03 UTC, nicolaspernoud commented
Hello, 
Same here, we need to get provider configuration from prisma (async) ...

2024-07-10 16:45 UTC, ThangHuuVu commented
@chrisivo @maiconcarraro @nicolaspernoud I opened a new PR to add support for asynchronous lazy init - thanks for flagging the issue