fix(kit): set cookies in getSession, introduce auth method
nextauthjs/next-auth pull request #9694
Opened 2024-01-20 14:41 UTC by ThangHuuVu

Closes #9497

- Rename `getSession` to `auth` to match `next-auth` return value
- Set the cookies from the Auth response before returning the session body
- Set a default value for `basePath` for SvelteKit - See #9686
- Upgrade the dev app to SvelteKit v2  

Fixes: #8034

2024-01-20 14:51 UTC, ndom91 commented on packages/frameworks-sveltekit/package.json
> +    "svelte": "^3.54.0 || ^4.0.0"
Svelte 5 betas are out, can we add support here already? :pray:

2024-01-20 14:54 UTC, ndom91 commented on packages/frameworks-sveltekit/package.json
> +    "svelte": "^3.54.0 || ^4.0.0"
```suggestion
    "svelte": "^3.54.0 || ^4.0.0" || "^5"
```

2024-01-20 14:57 UTC, balazsorban44 requested changes

2024-01-20 14:57 UTC, balazsorban44 commented on packages/core/src/lib/utils/web.ts
> +export function isAction(action: string): action is AuthAction {
```suggestion
function isAction(action: string): action is AuthAction {
```

2024-01-20 14:57 UTC, balazsorban44 commented on packages/frameworks-sveltekit/package.json
> +    "vendored",
```suggestion
```

2024-01-20 14:57 UTC, balazsorban44 commented on packages/frameworks-sveltekit/src/lib/index.ts
>    const request = new Request(url, { headers: req.headers })
```suggestion
  const request = new Request(url, {
    headers: { cookie: headers.get("cookie") ?? "" },
  })
```

2024-01-20 14:57 UTC, balazsorban44 commented on packages/frameworks-sveltekit/src/lib/index.ts
> +    _config.basePath ??= `${base}/auth`
This should be set in `setEnvDefaults`, and also respect `AUTH_URL` by default

2024-01-20 14:57 UTC, balazsorban44 commented on packages/frameworks-sveltekit/src/lib/index.ts
>        .split("/")[0] as AuthAction
```suggestion
      .split("/")[0]
```

We don't know the type here yet

2024-01-20 14:57 UTC, balazsorban44 commented on packages/frameworks-sveltekit/src/lib/index.ts
>      return Auth(request, _config)
```suggestion
    if (isAction(action) && url.pathname.startsWith(_config.basePath + "/")) {
        return Auth(request, _config)
    }
    return resolve(event)
```

Nit: let's flip the logic so we don't need the negation

2024-01-20 14:57 UTC, balazsorban44 commented on packages/frameworks-sveltekit/src/lib/index.ts
> +       */
```suggestion
      /** @deprecated Use `auth` instead. */
```

2024-01-20 14:57 UTC, balazsorban44 commented on packages/frameworks-sveltekit/src/lib/index.ts
> +  } catch {
This needs refactoring, `base` is not a full URL

2024-01-20 15:01 UTC, ndom91 approved these changes
LGTM :+1: 

*EDIT*: Ah didn't see Balazs' comments until after reload

2024-01-20 15:06 UTC, balazsorban44 commented on packages/frameworks-sveltekit/package.json
> +    "svelte": "^3.54.0 || ^4.0.0" || "^5"
```suggestion
    "svelte": "^3.54.0 || ^4.0.0 || ^5"
```

2024-01-20 15:14 UTC, merged

2024-02-23 02:33 UTC, ThangHuuVu commented
@kinglouie hi, if you see an issue, feel free to open an issue with a minimal reprodutible code and I will have a look 🙌

2024-03-01 20:53 UTC, socketopp commented on packages/frameworks-sveltekit/package.json
> +    "svelte": "^3.54.0 || ^4.0.0 || ^5"
@balazsorban44 

Currently trying out the new Svelte 5 alongside with @auth/sveltekit.
I am currently using "svelte": "^5.0.0-next.69" but it's complaining about peerDependency still.
```
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^3.54.0 || ^4.0.0 || ^5" from @auth/sveltekit@0.13.0
```

^5.0.0-next.69 should be working if ^5 is specfied right?