docs(dynamodb): add terraform template for dynamodb table
nextauthjs/next-auth pull request #9926
Opened 2024-02-06 11:01 UTC by junlarsen

## ☕️ Reasoning

Re-apply of https://github.com/nextauthjs/next-auth/pull/7586 per suggested by @ndom91  since that branch fell super far behind

I recently happened to use the DynamoDB adapter for NextAuth, and figured it could be helpful to add a template to the documentation, in line with the CDK and CloudFormation templates.

## 🧢 Checklist

- [x] Documentation
- [ ] Tests - N/A
- [ ] Ready to be merged

## 🎫 Affected issues

None

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

2024-02-06 15:19 UTC, ndom91 approved these changes
LGTM :+1:

2024-02-06 16:19 UTC, balazsorban44 requested changes
Left a small comment!

2024-02-07 09:42 UTC, junlarsen commented on packages/adapter-dynamodb/src/index.ts
> + * resource "aws_dynamodb_table" "next_auth" {
Of course. Would you also like me to re-name the CDK construct and CloudFormation template at the same time?

2024-04-08 10:30 UTC, ndom91 approved these changes
Awesome, thanks!

2024-04-08 21:29 UTC, ndom91 commented
Sorry but we're shipping new docs shortly and this change is already in, I'm going to close this PR :pray:

2024-04-08 21:29 UTC, closed without merging

2024-04-09 11:21 UTC, junlarsen commented
That's cool! Thanks for including it in the new docs